<div class="body_container">
	<div class="title-bar">
	    <h1 class="title-bar-title">Modelos más vendidos entre sucursales</h1>
	    <input type="text" id="btn_download" hidden="" disabled="">
	</div>
	<br>
	<br>

	<div class="row">
		<div class="col-md-8"></div>
		<div class="col-md-2 pull-right">
			<button id="btn_excel" class="btn btn-success"><span class="icon icon-file-excel-o"></span> EXCEL</button>

		</div>
	</div>

	<div class="col-md-3">
		<label class="col-sm-3 control-label" for="form-control-18">Sucursal</label>
		<select name="idsucursal[]" required="required" class="" tabindex="5">
			<?php foreach($sucursales as $id => $sucursal){?>
				<option value="<?php echo $id?>"><?php echo $sucursal?></option>
			<?php }?>
		</select>
	</div>

	<div class="row">
		<div class="col-md-3">
			<label class="col-sm-3 control-label" for="form-control-18">Desde</label>
			<?php echo $this->formDate($form->get('fecha_desde')) ?>
		</div>
		<div class="col-md-3">
			<label class="col-sm-3 control-label" for="form-control-18">Hasta</label>
			<?php echo $this->formDate($form->get('fecha_hasta')) ?>
		</div>
		

	</div>

	<div class="row">
		<div class="card-body">
		    <table id="" class="table table-striped table-nowrap dataTable" cellspacing="0" width="100%">
		        <thead>
		            <tr id='tittle_tr'>
		            	<?php foreach($sucursales as $id => $sucursal){?>
		            		<th id="<?php echo $id?>"><?php echo $sucursal?></th>
		            	<?php }?>
		            </tr>
		        </thead>
		        <tfoot>
		            <tr id='subtittle_tr'>
		               <?php foreach($sucursales as $id => $sucursal){?>
		            		<th><?php echo $sucursal?></th>
		            	<?php }?>
		            </tr>
		        </tfoot>
		        <tbody id="content_body">
		            
		        </tbody>
		    </table>
		</div>
	</div>

</div>
<script src="/js/reporte/administracion/comparacion/articulos.js"></script>
<script>
	var articulos = $('.body_container').articulos();
	articulos.list();
</script>
