<div class="body_container">
	<div class="title-bar">
	    <h1 class="title-bar-title">Pedidos completados por producto</h1>
	    
	</div>

	<?php foreach ($messages->getSuccessMessages() as $message):?>
	        <div class="alert alert-success alert-dismissable">
	            <button class="close" aria-hidden="true" data-dismiss="alert" type="button"></button>
	            <strong>Éxito!</strong>
	            <?php echo $message?>
	        </div>
	<?php endforeach;?>

	<?php foreach ($messages->geterrorMessages() as $message):?>
	        <div class="alert alert-danger alert-dismissable">
	            <button class="close" aria-hidden="true" data-dismiss="alert" type="button"></button>
	            <strong>Error!</strong>
	            <?php echo $message?>
	        </div>
	<?php endforeach;?>




	<!--<div class="row">
		<div class="col-md-12">
			<a class="btn btn-bg btn-success btn-labeled pull-right" href="/catalogo/medidas/nuevo">
              Agregar
              <span class="btn-label btn-label-right">
                <span class="icon icon-plus-square icon-lg icon-fw"></span>
              </span>
            </a>
		</div>
	</div>-->

	<div class="row">
		<div class="card-body">
			<input type="hidden" name="idproducto" value="<?php echo $id ?>">
		    <table id="" class="table table-bordered table-nowrap dataTable" cellspacing="0" width="100%">
		        <thead>
		            <tr>
		                <th>Variante</th>
		                <th>Fotografía</th>
		                <th>7.0</th>
		                <th>7.5</th>
		                <th>8.0</th>
		                <th>8.5</th>
		                <th>9.0</th>
		                <th>9.5</th>
		                <th>10.0</th>
		                <th>10.5</th>
		                <th>11.0</th>
		                <th>11.5</th>
		                <th>12.0</th>
		                <th>12.5</th>
		                <th>13.0</th>
		                <th>13.5</th>
		                <th>14.0</th>
		                <th>14.5</th>
		                <th>15.0</th>
		                <th>15.5</th>
		                <th>16.0</th>
		                <th>16.5</th>
		                <th>17.0</th>
		                <th>17.5</th>
		                <th>18.0</th>
		                <th>18.5</th>
		                <th>19.0</th>
		                <th>19.5</th>
		                <th>20.0</th>
		                <th>20.5</th>
		                <th>21.0</th>
		                <th>21.5</th>
		                <th>22.0</th>
		                <th>22.5</th>
		                <th>23.0</th>
		                <th>23.5</th>
		                <th>24.0</th>
		                <th>24.5</th>
		                <th>25.0</th>
		                <th>25.5</th>
		                <th>26.0</th>
		                <th>26.5</th>
		                <th>27.0</th>
		                <th>27.5</th>
		                <th>28.0</th>
		                <th>28.5</th>
		                <th>29.0</th>
		                <th>29.5</th>
		                <th>30.0</th>
		                <th>30.5</th>
		                <th>31.0</th>
		                <th>31.5</th>
		                <th>32.0</th>
		                <th>32.5</th>
		                <th>33.0</th>
		                <th>33.5</th>
		                <th>34.0</th>
		                <th>34.5</th>
		                <th>35.0</th>
		                	
		            </tr>
		        </thead>
		        <tfoot>
		            <tr>
		                <th>Variante</th>
		                <th>Fotografía</th>
		                <th>7.0</th>
		                <th>7.5</th>
		                <th>8.0</th>
		                <th>8.5</th>
		                <th>9.0</th>
		                <th>9.5</th>
		                <th>10.0</th>
		                <th>10.5</th>
		                <th>11.0</th>
		                <th>11.5</th>
		                <th>12.0</th>
		                <th>12.5</th>
		                <th>13.0</th>
		                <th>13.5</th>
		                <th>14.0</th>
		                <th>14.5</th>
		                <th>15.0</th>
		                <th>15.5</th>
		                <th>16.0</th>
		                <th>16.5</th>
		                <th>17.0</th>
		                <th>17.5</th>
		                <th>18.0</th>
		                <th>18.5</th>
		                <th>19.0</th>
		                <th>19.5</th>
		                <th>20.0</th>
		                <th>20.5</th>
		                <th>21.0</th>
		                <th>21.5</th>
		                <th>22.0</th>
		                <th>22.5</th>
		                <th>23.0</th>
		                <th>23.5</th>
		                <th>24.0</th>
		                <th>24.5</th>
		                <th>25.0</th>
		                <th>25.5</th>
		                <th>26.0</th>
		                <th>26.5</th>
		                <th>27.0</th>
		                <th>27.5</th>
		                <th>28.0</th>
		                <th>28.5</th>
		                <th>29.0</th>
		                <th>29.5</th>
		                <th>30.0</th>
		                <th>30.5</th>
		                <th>31.0</th>
		                <th>31.5</th>
		                <th>32.0</th>
		                <th>32.5</th>
		                <th>33.0</th>
		                <th>33.5</th>
		                <th>34.0</th>
		                <th>34.5</th>
		                <th>35.0</th>
		                	
		    
		            </tr>
		        </tfoot>
		        <tbody>
		            
		        </tbody>
		    </table>
		</div>
	</div>

</div>
<script type="text/javascript" src="https://cdn.jsdelivr.net/sweetalert2/6.4.2/sweetalert2.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/sweetalert2/6.4.2/sweetalert2.min.css">

<script src="/js/pedido/pedidos_completados_producto.js"></script>

<script>
	var pedidos_completados_producto = $('.body_container').pedidos_completados_producto();
	pedidos_completados_producto.list(<?php echo $id ?>);
</script>
