<div class="body_container">
	<div class="title-bar">
	    <h1 class="title-bar-title">Tallajes - Agregar</h1>
	</div>
    <div class="row">
        <div class="col-md-offset-1 col-md-10">
    		<div class="demo-form-wrapper">
    			<form class="form form-horizontal" action="/catalogo/tallajes/nuevo" method="POST">
	    			<div class="col-xs-10">
		       			<div class="form-group">
			           		<label  for="Nombre">Nombre del tallaje</label>
			                <?php echo $this->formText($form->get('tallaje_nombre')) ?>
		        		</div>


			        	<div class="form-group">
			        		<label  for="Tallas">Seleccione las tallas</label>
			        	
				        	<div class="row" >
				        		<table class="table table-bordered">

								    <tbody>
								      <tr>
								        <td>
								        	<label style="text-align: center; display: block">7.0 </label>
		                					<?php echo $this->formCheckbox($form->get('talla_70')) ?>
								        </td>

								        <td>
								        	<label style="text-align: center; display: block">7.5 </label>
		                					<?php echo $this->formCheckbox($form->get('talla_75')) ?>
								        </td>

								        <td>
								        	<label style="text-align: center; display: block">8.0 </label>
		                					<?php echo $this->formCheckbox($form->get('talla_80')) ?>
								        </td>

								        <td>
								        	<label style="text-align: center; display: block">8.5 </label>
		                					<?php echo $this->formCheckbox($form->get('talla_85')) ?>
								        </td>

								        <td>
								        	<label style="text-align: center; display: block">9.0 </label>
		                					<?php echo $this->formCheckbox($form->get('talla_90')) ?>
								        </td>

								        <td>
								        	<label style="text-align: center; display: block">9.5 </label>
		                					<?php echo $this->formCheckbox($form->get('talla_95')) ?>
								        </td>

								        <td>
								        	<label style="text-align: center; display: block">10.0 </label>
		                					<?php echo $this->formCheckbox($form->get('talla_100')) ?>
								        </td>

								        <td>
								        	<label style="text-align: center; display: block">10.5 </label>
		                					<?php echo $this->formCheckbox($form->get('talla_105')) ?>
								        </td>

								        <td>
								        	<label style="text-align: center; display: block">11.0 </label>
		                					<?php echo $this->formCheckbox($form->get('talla_110')) ?>
								        </td>

								        <td>
								        	<label style="text-align: center; display: block">11.5 </label>
		                					<?php echo $this->formCheckbox($form->get('talla_115')) ?>
								        </td>

								      </tr>
								       <tr>
								        <td>
								        	<label style="text-align: center; display: block">12.0 </label>
		                					<?php echo $this->formCheckbox($form->get('talla_120')) ?>
								        </td>

								        <td>
								        	<label style="text-align: center; display: block">12.5 </label>
		                					<?php echo $this->formCheckbox($form->get('talla_125')) ?>
								        </td>

								        <td>
								        	<label style="text-align: center; display: block">13.0 </label>
		                					<?php echo $this->formCheckbox($form->get('talla_130')) ?>
								        </td>

								        <td>
								        	<label style="text-align: center; display: block">13.5 </label>
		                					<?php echo $this->formCheckbox($form->get('talla_135')) ?>
								        </td>

								        <td>
								        	<label style="text-align: center; display: block">14.0 </label>
		                					<?php echo $this->formCheckbox($form->get('talla_140')) ?>
								        </td>

								        <td>
								        	<label style="text-align: center; display: block">14.5 </label>
		                					<?php echo $this->formCheckbox($form->get('talla_145')) ?>
								        </td>

								        <td>
								        	<label style="text-align: center; display: block">15.0 </label>
		                					<?php echo $this->formCheckbox($form->get('talla_150')) ?>
								        </td>

								        <td>
								        	<label style="text-align: center; display: block">15.5 </label>
		                					<?php echo $this->formCheckbox($form->get('talla_155')) ?>
								        </td>

								        <td>
								        	<label style="text-align: center; display: block">16.0 </label>
		                					<?php echo $this->formCheckbox($form->get('talla_160')) ?>
								        </td>

								        <td>
								        	<label style="text-align: center; display: block">16.5 </label>
		                					<?php echo $this->formCheckbox($form->get('talla_165')) ?>
								        </td>

								      </tr>

								       <tr>
								        <td>
								        	<label style="text-align: center; display: block">17.0 </label>
		                					<?php echo $this->formCheckbox($form->get('talla_170')) ?>
								        </td>

								        <td>
								        	<label style="text-align: center; display: block">17.5 </label>
		                					<?php echo $this->formCheckbox($form->get('talla_175')) ?>
								        </td>

								        <td>
								        	<label style="text-align: center; display: block">18.0 </label>
		                					<?php echo $this->formCheckbox($form->get('talla_180')) ?>
								        </td>

								        <td>
								        	<label style="text-align: center; display: block">18.5 </label>
		                					<?php echo $this->formCheckbox($form->get('talla_185')) ?>
								        </td>

								        <td>
								        	<label style="text-align: center; display: block">19.0 </label>
		                					<?php echo $this->formCheckbox($form->get('talla_190')) ?>
								        </td>

								        <td>
								        	<label style="text-align: center; display: block">19.5 </label>
		                					<?php echo $this->formCheckbox($form->get('talla_195')) ?>
								        </td>

								        <td>
								        	<label style="text-align: center; display: block">20.0 </label>
		                					<?php echo $this->formCheckbox($form->get('talla_200')) ?>
								        </td>

								        <td>
								        	<label style="text-align: center; display: block">20.5 </label>
		                					<?php echo $this->formCheckbox($form->get('talla_205')) ?>
								        </td>

								        <td>
								        	<label style="text-align: center; display: block">21.0 </label>
		                					<?php echo $this->formCheckbox($form->get('talla_210')) ?>
								        </td>

								        <td>
								        	<label style="text-align: center; display: block">21.5 </label>
		                					<?php echo $this->formCheckbox($form->get('talla_215')) ?>
								        </td>

								      </tr>


								       <tr>
								        <td>
								        	<label style="text-align: center; display: block">22.0 </label>
		                					<?php echo $this->formCheckbox($form->get('talla_220')) ?>
								        </td>

								        <td>
								        	<label style="text-align: center; display: block">22.5 </label>
		                					<?php echo $this->formCheckbox($form->get('talla_225')) ?>
								        </td>

								        <td>
								        	<label style="text-align: center; display: block">23.0 </label>
		                					<?php echo $this->formCheckbox($form->get('talla_230')) ?>
								        </td>

								        <td>
								        	<label style="text-align: center; display: block">23.5 </label>
		                					<?php echo $this->formCheckbox($form->get('talla_235')) ?>
								        </td>

								        <td>
								        	<label style="text-align: center; display: block">24.0 </label>
		                					<?php echo $this->formCheckbox($form->get('talla_240')) ?>
								        </td>

								        <td>
								        	<label style="text-align: center; display: block">24.5 </label>
		                					<?php echo $this->formCheckbox($form->get('talla_245')) ?>
								        </td>

								        <td>
								        	<label style="text-align: center; display: block">25.0 </label>
		                					<?php echo $this->formCheckbox($form->get('talla_250')) ?>
								        </td>

								        <td>
								        	<label style="text-align: center; display: block">25.5 </label>
		                					<?php echo $this->formCheckbox($form->get('talla_255')) ?>
								        </td>

								        <td>
								        	<label style="text-align: center; display: block">26.0 </label>
		                					<?php echo $this->formCheckbox($form->get('talla_260')) ?>
								        </td>

								        <td>
								        	<label style="text-align: center; display: block">26.5 </label>
		                					<?php echo $this->formCheckbox($form->get('talla_265')) ?>
								        </td>

								      </tr>


								       <tr>
								        <td>
								        	<label style="text-align: center; display: block">27.0 </label>
		                					<?php echo $this->formCheckbox($form->get('talla_270')) ?>
								        </td>

								        <td>
								        	<label style="text-align: center; display: block">27.5 </label>
		                					<?php echo $this->formCheckbox($form->get('talla_275')) ?>
								        </td>

								        <td>
								        	<label style="text-align: center; display: block">28.0 </label>
		                					<?php echo $this->formCheckbox($form->get('talla_280')) ?>
								        </td>

								        <td>
								        	<label style="text-align: center; display: block">28.5 </label>
		                					<?php echo $this->formCheckbox($form->get('talla_285')) ?>
								        </td>

								        <td>
								        	<label style="text-align: center; display: block">29.0 </label>
		                					<?php echo $this->formCheckbox($form->get('talla_290')) ?>
								        </td>

								        <td>
								        	<label style="text-align: center; display: block">29.5 </label>
		                					<?php echo $this->formCheckbox($form->get('talla_295')) ?>
								        </td>

								        <td>
								        	<label style="text-align: center; display: block">30.0 </label>
		                					<?php echo $this->formCheckbox($form->get('talla_300')) ?>
								        </td>

								        <td>
								        	<label style="text-align: center; display: block">30.5 </label>
		                					<?php echo $this->formCheckbox($form->get('talla_305')) ?>
								        </td>

								        <td>
								        	<label style="text-align: center; display: block">31.0 </label>
		                					<?php echo $this->formCheckbox($form->get('talla_310')) ?>
								        </td>

								        <td>
								        	<label style="text-align: center; display: block">31.5 </label>
		                					<?php echo $this->formCheckbox($form->get('talla_315')) ?>
								        </td>

								      </tr>

								      <tr>
								      	<td>
								        	<label style="text-align: center; display: block">32.0 </label>
		                					<?php echo $this->formCheckbox($form->get('talla_320')) ?>
								        </td>

								        <td>
								        	<label style="text-align: center; display: block">32.5 </label>
		                					<?php echo $this->formCheckbox($form->get('talla_325')) ?>
								        </td>

								        <td>
								        	<label style="text-align: center; display: block">33.0 </label>
		                					<?php echo $this->formCheckbox($form->get('talla_330')) ?>
								        </td>

								        <td>
								        	<label style="text-align: center; display: block">33.5 </label>
		                					<?php echo $this->formCheckbox($form->get('talla_335')) ?>
								        </td>

								        <td>
								        	<label style="text-align: center; display: block">34.0 </label>
		                					<?php echo $this->formCheckbox($form->get('talla_340')) ?>
								        </td>

								        <td>
								        	<label style="text-align: center; display: block">34.5 </label>
		                					<?php echo $this->formCheckbox($form->get('talla_345')) ?>
								        </td>

								        <td>
								        	<label style="text-align: center; display: block">35.0 </label>
		                					<?php echo $this->formCheckbox($form->get('talla_350')) ?>
								        </td>
								      </tr>

								    </tbody>
								</table>

							</div>
			        	</div>
		        	
	        	


		     

		        	<div class="form-group">
		           		<label  for="guardar"></label>
		                <button class="btn btn-primary btn-block btn-next" type="submit">Guardar</button>
	        		</div>
 
    			</form>
    		</div>
    	</div>
	</div>
</div>
<script type="text/javascript">
	$(document).ready(function() {
	  $('form').on('submit', function(e) {
	    $(this).find('button, input[type=button]').prop('disabled', true);
	  });
	});
</script>