<div class="body_container">
	<div class="title-bar">
	    <h1 class="title-bar-title">Tallajes - Agregar</h1>
	</div>
    <div class="row">
        <div class="col-md-offset-1 col-md-10">
    		<div class="demo-form-wrapper">
    			<form class="form form-horizontal" action="/catalogo/tallajes/nuevo" method="POST">
	    			<div class="col-xs-10">
		       			<div class="form-group">
			           		<label  for="Nombre">Nombre del tallaje</label>
			                <?php echo $this->formText($form->get('tallaje_nombre')) ?>
		        		</div>


			        	<div class="form-group">
			        		<label  for="Tallas">Seleccione las tallas</label>
			        	
				        	<div class="row">
				        		<div class="col-xs-1"></div>

				        		<div class="col-xs-1">
				        			 <?php echo $this->formCheckbox($form->get('talla_70')) ?>
				        		</div>

				        		<div class="col-xs-1">
				        			 <?php echo $this->formCheckbox($form->get('talla_70')) ?>
				        		</div>
				        		
				        		<div class="col-xs-1">s</div>
				        		<div class="col-xs-1">s</div>
				        		<div class="col-xs-1">s</div>
				        		<div class="col-xs-1">s</div>
				        		<div class="col-xs-1">s</div>
				        		<div class="col-xs-1">s</div>
				        		<div class="col-xs-1">s</div>
				        		<div class="col-xs-1">s</div>
				        		<div class="col-xs-1"></div>

				        	</div>

				        	<div class="row">
				        		<div class="col-xs-1"></div>
				        		<div class="col-xs-1">s</div>
				        		<div class="col-xs-1">s</div>
				        		<div class="col-xs-1">s</div>
				        		<div class="col-xs-1">s</div>
				        		<div class="col-xs-1">s</div>
				        		<div class="col-xs-1">s</div>
				        		<div class="col-xs-1">s</div>
				        		<div class="col-xs-1">s</div>
				        		<div class="col-xs-1">s</div>
				        		<div class="col-xs-1">s</div>
				        		<div class="col-xs-1"></div>

				        	</div>

				        	<div class="row">
				        		<div class="col-xs-1"></div>
				        		<div class="col-xs-1">s</div>
				        		<div class="col-xs-1">s</div>
				        		<div class="col-xs-1">s</div>
				        		<div class="col-xs-1">s</div>
				        		<div class="col-xs-1">s</div>
				        		<div class="col-xs-1">s</div>
				        		<div class="col-xs-1">s</div>
				        		<div class="col-xs-1">s</div>
				        		<div class="col-xs-1">s</div>
				        		<div class="col-xs-1">s</div>
				        		<div class="col-xs-1"></div>

				        	</div>

				        	<div class="row">
				        		<div class="col-xs-1"></div>
				        		<div class="col-xs-1">s</div>
				        		<div class="col-xs-1">s</div>
				        		<div class="col-xs-1">s</div>
				        		<div class="col-xs-1">s</div>
				        		<div class="col-xs-1">s</div>
				        		<div class="col-xs-1">s</div>
				        		<div class="col-xs-1">s</div>
				        		<div class="col-xs-1">s</div>
				        		<div class="col-xs-1">s</div>
				        		<div class="col-xs-1">s</div>
				        		<div class="col-xs-1"></div>

				        	</div>

				        	<div class="row">
				        		<div class="col-xs-1"></div>
				        		<div class="col-xs-1">s</div>
				        		<div class="col-xs-1">s</div>
				        		<div class="col-xs-1">s</div>
				        		<div class="col-xs-1">s</div>
				        		<div class="col-xs-1">s</div>
				        		<div class="col-xs-1">s</div>
				        		<div class="col-xs-1">s</div>
				        		<div class="col-xs-1">s</div>
				        		<div class="col-xs-1">s</div>
				        		<div class="col-xs-1">s</div>
				        		<div class="col-xs-1"></div>

				        	</div>
			        	</div>
		        	
	        	


		     

		        	<div class="form-group">
		           		<label  for="guardar"></label>
		                <button class="btn btn-primary btn-block btn-next" type="submit">Guardar</button>
	        		</div>
 
    			</form>
    		</div>
    	</div>
	</div>
</div>
