<div class="body_container">
	<div class="title-bar">
	</div>

	<?php foreach ($messages->getSuccessMessages() as $message):?>
	        <div class="alert alert-success alert-dismissable">
	            <button class="close" aria-hidden="true" data-dismiss="alert" type="button"></button>
	            <strong>Éxito!</strong>
	            <?php echo $message?>
	        </div>
	<?php endforeach;?>
    <div class="row">
        <div class="col-md-offset-1 col-md-10">
    		<div class="demo-form-wrapper">
    			<form class="form form-horizontal" action="/configuraciones/actualizar" method="POST">
	       			<div class="panel panel-info">
		                <div class="panel-heading"><h4>CONFIGURACIONES</h4></div>

		                 <div class="panel-body">
		                    <div class="form-group">
		                        <label class="col-sm-3 control-label" for="form-control-18">Descuento</label>
		                        <div class="col-sm-8">

		                            <input name="configuracion_descuentosat" required="required" class="form-control infput-thick" value="<?php echo $desc ?>" type="text">		                        
		                        </div>
		                    </div>

		                    
		                </div>
		            </div>


		            

		            <div class="form-group">
		                <label  for="guardar"></label>
		                <button class="btn btn-primary btn-block btn-next" type="submit" tabindex="23">ACTUALIZAR</button>
		            </div>
 
    			</form>
    		</div>
    	</div>
	</div>
</div>

<script type="text/javascript">
	$('input[name=configuracion_descuentosat]').numeric();
</script>
