<div class="body_container">
	<div class="title-bar">
	    <h1 class="title-bar-title">Productos - Agregar</h1>
	</div>
    <div class="row">
        <div class="col-md-offset-1 col-md-10">
    		<div class="demo-form-wrapper">
    			<form class="form form-horizontal" name="formulario" action="/catalogo/productos/nuevo" method="POST">
    				<div class="row">
		    			<div class="col-md-5">
			       			<div class="form-group">
				           		<label  for="Modelo">Modelo </label>
				                <?php echo $this->formText($form->get('producto_modelo')) ?>
			        		</div>

			        		<div class="form-group">
				           		<label  for="dirigido"> Dirigido a:</label>
				                <?php echo $this->formSelect($form->get('producto_dirigidoa')) ?>
			        		</div>

			        		<div class="form-group">
				           		<label  for="tipo">Tipo de calzado</label>
				                <?php echo $this->formSelect($form->get('idtipocalzado')) ?>
			        		</div>

			        		<div class="form-group">
				           		<label  for="venta">Precio de venta</label>
				                <?php echo $this->formText($form->get('producto_precioventa')) ?>
			        		</div>

			        		<div class="form-group">
				           		<label  for="minimo">Mínimo</label>
				                <?php echo $this->formText($form->get('producto_minimo')) ?>
			        		</div>

			        		<div class="form-group">
				           		<label  for="comisionable">Comisionable</label>
				                <?php echo $this->formSelect($form->get('producto_comisionable')) ?>
			        		</div>
			        		
			        	</div>
			        	<div class="col-md-1"></div>
		        		<div class="col-md-5">
			       			<div class="form-group">
				           		<label  for="Proveedor">Proveedor </label>
				                <?php echo $this->formSelect($form->get('idproveedor')) ?>
			        		</div>

			        		<div class="form-group">
				           		<label  for="marca"> Marca</label>
				                <?php echo $this->formSelect($form->get('idmarca')) ?>
			        		</div>

			        		<div class="form-group">
				           		<label  for="Temporada">Temporada</label>
				                <?php echo $this->formSelect($form->get('idtemporada')) ?>
			        		</div>

			        		<div class="form-group">
				           		<label  for="mayoreo">Precio mayoreo</label>
				                <?php echo $this->formText($form->get('producto_preciomayoreo')) ?>
			        		</div>

			        		<div class="form-group">
				           		<label  for="reorden">Reorden</label>
				                <?php echo $this->formText($form->get('producto_reorden')) ?>
			        		</div>

			        		
			        	</div>
		        	
 					</div> <!--end class row-->

 					<div class="row">
		        		
    					<div class="col-md-5 alineamiento" >

		        				<div class="col-md-9">
				                    <div class="form-group">
						           		<label for="tallaje">Tallaje</label>
						                <?php echo $this->formSelect($form->get('idtallaje[]')) ?>
					        		</div>
		        				</div>
		        				<div class="col-md-1"></div>
				        		<div class="col-md-2">		
				        			<div class="form-group">
						           		<label  for="guardar"></label>
                                                                        <a class="btn btn-primary btn-block btn-next" id="btn_add_tallaje">Agregar</a>
					        		</div>
					        	</div>

                                                        <table class="table table-bordered" id="tabla_tallaje">
	        				    <thead>
	        				      <tr>
	        				        <th>Nombre</th>
	        				        <th>Opciones</th>
	        				      </tr>
	        				    </thead>
	        				    <tbody>
 
	        				    </tbody>
	        				  </table>
	        				

	        				
		        				<div class="col-md-9">
				                    <div class="form-group">
						           		<label for="tallaje">Materiales</label>
						                <?php echo $this->formSelect($form->get('idmaterial[]')) ?>
					        		</div>
		        				</div>
		        				<div class="col-md-1"></div>
				        		<div class="col-md-2">		
				        			<div class="form-group">
						           		<label  for="guardar"></label>
						                <button class="btn btn-primary btn-block btn-next" type="submit">Agregar</button>
					        		</div>
					        	</div>

					        	<table class="table table-bordered">
	        				    <thead>
	        				      <tr>
	        				        <th>Nombre</th>
	        				        <th>Opciones</th>
	        				      </tr>
	        				    </thead>
	        				    <tbody>
	        				      <tr>
	        				        <td>Cuero</td>
	        				        <td>Eliminar</td>
	        				      </tr>
	        				      
	        				    </tbody>
	        				  </table>
	        				


	        			</div>	
	        			<div class="col-md-1"></div>
	        			<div class="col-md-5 alineamiento" >
	        				
		        				<div class="col-md-9">
				                    <div class="form-group">
						           		<label for="tallaje">Colores</label>
						                <?php echo $this->formSelect($form->get('idcolor[]')) ?>
					        		</div>
		        				</div>
		        				<div class="col-md-1"></div>
				        		<div class="col-md-2">		
				        			<div class="form-group">
						           		<label  for="guardar"></label>
						                <button class="btn btn-primary btn-block btn-next" type="submit">Agregar</button>
					        		</div>
					        	</div>

					        	<table class="table table-bordered">
	        				    <thead>
	        				      <tr>
	        				        <th>Nombre</th>
	        				        <th>Opciones</th>
	        				      </tr>
	        				    </thead>
	        				    <tbody>
	        				      <tr>
	        				        <td>Negro</td>
	        				        <td>Eliminar</td>
	        				      </tr>
	        				      
	        				    </tbody>
	        				  </table>
	        				

	        			</div>

		        	</div>


		        	<div class="form-group">
		           		<label  for="guardar"></label>
                                        <button class="btn btn-primary btn-block btn-next" type="submit">Guardar</button>
	        		</div>
 
    			</form>
    		</div>
    	</div>
	</div>


	

   

</div>


<script src="/js/catalogo/productos.js"></script>
<script>
	var productos = $('.body_container').productos();
	productos.initForm();
</script>
