<div class="body_container">
	<div class="title-bar">
	    <h1 class="title-bar-title">Marcas por proveedor</h1>
	    <input type="text" id="btn_download" hidden="" disabled="">
	</div>
	<br>
	<br>

	<div class="row">
		<div class="col-md-8"></div>
		<div class="col-md-2 pull-right">
			<button id="btn_excel" class="btn btn-success"><span class="icon icon-file-excel-o"></span> EXCEL</button>

		</div>
	</div>


	<div class="row">
		<div class="card-body">
		    <table id="" class="table table-striped table-nowrap dataTable" cellspacing="0" width="100%">
		        <thead>
		            <tr>
		                <th>Proveedor</th>
		                <th>Marca</th>
		            </tr>
		        </thead>
		        <tfoot>
		            <tr>
		                <th>Proveedor</th>
		                <th>Marca</th>
		            </tr>
		        </tfoot>
		        <tbody>
		            
		        </tbody>
		    </table>
		</div>
	</div>

</div>
<script src="/js/reporte/administracion/marcasProveedor.js"></script>
<script>
	var marcasProveedor = $('.body_container').marcasProveedor();
	marcasProveedor.list();
</script>
