<div class="body_container">
	<div class="title-bar">
	    <h1 class="title-bar-title">Modelos más vendidos por tienda</h1>
	    <input type="text" id="btn_download" hidden="" disabled="">
	</div>
	<br>
	<br>

	<div class="row">
		<div class="col-md-8"></div>
		<div class="col-md-2 pull-right">
			<button id="btn_excel" class="btn btn-success"><span class="icon icon-file-excel-o"></span> EXCEL</button>

		</div>
	</div>


	<div class="row">
		<div class="col-md-3">
			<label class="col-sm-3 control-label" for="form-control-18">Desde</label>
			<?php echo $this->formDate($form->get('fecha_desde')) ?>
		</div>
		<div class="col-md-3">
			<label class="col-sm-3 control-label" for="form-control-18">Hasta</label>
			<?php echo $this->formDate($form->get('fecha_hasta')) ?>
		</div>
		<div class="col-md-3">
			<label class="col-sm-3 control-label" for="form-control-18">Estatus</label>
			<select name="idsucursal[]" required="required" class="" tabindex="5">
				<?php foreach($sucursales as $id => $sucursal){?>
					<option value="<?php echo $id?>"><?php echo $sucursal?></option>
				<?php }?>
			</select>
		</div>
	</div>

	<div class="row">
		<div class="card-body">
		    <table id="" class="table table-striped table-nowrap dataTable" cellspacing="0" width="100%">
		        <thead>
		            <tr>
		                <th>Sucursal</th>
		                <th>Modelo</th>
		                <th>Cantidad</th>
		            </tr>
		        </thead>
		        <tfoot>
		            <tr>
		                <th>Sucursal</th>
		                <th>Modelo</th>
		                <th>Cantidad</th>
		            </tr>
		        </tfoot>
		        <tbody>
		            
		        </tbody>
		    </table>
		</div>
	</div>

</div>
<script src="/js/reporte/administracion/masVendidosSucursal.js"></script>
<script>
	var masVendidosSucursal = $('.body_container').masVendidosSucursal();
	masVendidosSucursal.list();
</script>
