<div class="body_container">
	<div class="title-bar">
	    <h1 class="title-bar-title">Empleados - Agregar</h1>
	</div>
    <div class="row">
        <div class="col-md-offset-1 col-md-10">
    		<div class="demo-form-wrapper">
    			<form class="form form-horizontal" action="/catalogo/empleados/nuevo" method="POST">


    				<div class="panel panel-info">
						<div class="panel-heading"><h4>DATOS PERSONALES</h4></div>

						 <div class="panel-body">
		          			<div class="col-xs-5">

		      	        		<div class="form-group">
					           		<label  for="Nombre">Nombre</label>
					                <?php echo $this->formText($form->get('empleado_nombre')) ?>
				        		</div>

				        		<div class="form-group">
					           		<label  for="materno">Apellido materno</label>
					                <?php echo $this->formText($form->get('empleado_amaterno')) ?>
				        		</div>



				        		<div class="form-group">
					           		<label  for="CURP">CURP</label>
					                <?php echo $this->formText($form->get('empleado_curp')) ?>
				        		</div>

				        		<div class="form-group">
					           		<label  for="Username">Username</label>
					                <?php echo $this->formText($form->get('empleado_username')) ?>
				        		</div>

				        		<div class="form-group">
					           		<label  for="Email">Email</label>
					                <?php echo $this->formText($form->get('empleado_email')) ?>
				        		</div>




		      	        	</div>

		      	        	<div class="col-xs-1"></div>

		      	        	<div class="col-xs-5">

		      	        		<div class="form-group">
					           		<label  for="paterno">Apellido paterno</label>
					                <?php echo $this->formText($form->get('empleado_apaterno')) ?>
				        		</div>


	   			       			<div class="form-group">
					           		<label  for="Telefono">Teléfono</label>
					                <?php echo $this->formText($form->get('empleado_telefono')) ?>
				        		</div>

				        		<div class="form-group">
					           		<label  for="Fecha de nacimiento">Fecha de nacimiento</label>
					                <?php echo $this->formDate($form->get('empleado_fechanacimiento')) ?>
				        		</div>

				        		<div class="form-group">
					           		<label  for="Password">Password</label>
					                <?php echo $this->formPassword($form->get('empleado_password')) ?>
				        		</div>


		      	        	</div>
						</div>
					</div>
					<br>

    				<div class="panel panel-info">
						<div class="panel-heading"><h4>DIRECCIÓN</h4></div>

						 <div class="panel-body">
		          			<div class="col-xs-5">

		      	        		<div class="form-group">
					           		<label  for="Estado">Estado</label>
					                <?php echo $this->formText($form->get('empleado_estado')) ?>
				        		</div>

				        		<div class="form-group">
					           		<label  for="Colonia">Colonia</label>
					                <?php echo $this->formText($form->get('empleado_colonia')) ?>
				        		</div>

				        		<div class="form-group">
					           		<label  for="Calle">Calle</label>
					                <?php echo $this->formText($form->get('empleado_calle')) ?>
				        		</div>

				        		<div class="form-group">
					           		<label  for="Número exterior">Número exterior</label>
					                <?php echo $this->formText($form->get('empleado_numexterno')) ?>
				        		</div>

		      	        	</div>

		      	        	<div class="col-xs-1"></div>

		      	        	<div class="col-xs-5">
	   			       			<div class="form-group">
					           		<label  for="Ciudad">Ciudad</label>
					                <?php echo $this->formText($form->get('empleado_ciudad')) ?>
				        		</div>

				        		<div class="form-group">
					           		<label  for="Código postal">Código postal</label>
					                <?php echo $this->formText($form->get('empleado_codigopostal')) ?>
				        		</div>

				        		<div class="form-group">
					           		<label  for="Número interior">Número interior</label>
					                <?php echo $this->formText($form->get('empleado_numinterno')) ?>
				        		</div>
		      	        	</div>
						</div>
					</div>


					<div class="panel panel-info">
						<div class="panel-heading"><h4>DATOS FISCALES</h4></div>

						 <div class="panel-body">
		          			<div class="col-xs-5">

		          				<div class="form-group">
					           		<label  for="NSS">NSS</label>
					                <?php echo $this->formText($form->get('empleado_nss')) ?>
				        		</div>

				        		<div class="form-group">
					           		<label  for="ESTATUS">Estatus</label>
					                <?php echo $this->formSelect($form->get('empleado_estatus')) ?>
				        		</div>

				        		<div class="form-group">
					           		<label  for="Comision">Comision</label>
					                <?php echo $this->formSelect($form->get('empleado_comision')) ?>
				        		</div>
										<div class="form-group">
												<label  for="Sucursal">Sucursal Asignada</label>
													<?php
													echo $this->formSelect($form->get('idsucursal')) 
													?>
										</div>

		      	        	</div>

		      	        	<div class="col-xs-1"></div>

		      	        	<div class="col-xs-5">


	   			       			<div class="form-group">
					           		<label  for="Rol">Rol</label>
					                <?php echo $this->formSelect($form->get('idrol')) ?>
				        		</div>


				        		<div class="form-group">
					           		<label  for="RFC">RFC</label>
					                <?php echo $this->formText($form->get('empleado_rfc')) ?>
				        		</div>

				        		<div class="form-group">
					           		<label  for="Fecha de entrada">Fecha de entrada</label>
					                <?php echo $this->formDate($form->get('empleado_fechaentrada')) ?>
				        		</div>
		      	        	</div>
						</div>
					</div>





		        	<div class="form-group">
		           		<label  for="guardar"></label>
		                <button class="btn btn-primary btn-block btn-next" type="submit" tabindex="23">Guardar</button>
	        		</div>

    			</form>
    		</div>
    	</div>
	</div>
</div>
<script src="/js/catalogo/empleados.js"></script>
<script>
	var empleados = $('.body_container').empleados();
	empleados.initForm();
</script>

<script type="text/javascript">
	$(document).ready(function() {
	  $('form').on('submit', function(e) {
	    $(this).find('button, input[type=button]').prop('disabled', true);
	  });
	});
</script>
