<div class="body_container">
	<div class="title-bar">
	    <h1 class="title-bar-title">  Proveedor: <?php echo $entity->getProveedor()->getProveedorNombrecomercial() ?> - Folio: <?php echo $entity->getIdcompra() ?> </h1>
	    <h2 class="title-bar-title"> Total: <label>$<?php echo money_format('%.2n', $entity->getCompraTotal())?> </label>, Restante: <label id="restante">$<?php echo $restante?></label></h2>
	</div>
    <div class="row">
        <div class="col-md-offset-1 col-md-10">
    		<div class="demo-form-wrapper">
    			
				<div class="row">
	    			<div class="col-md-5">
	    			<input type="hidden" name="idcompra" value="<?php echo $entity->getIdcompra()?>">
		       			<div class="form-group">
			           		<label  for="fecha">Fecha </label>
			                <?php echo $this->formDate($form->get('cuentabancariamovimiento_fechamovimiento')) ?>
		        		</div>

		        		<div class="form-group">
			           		<label  for="cantidad"> Cantidad </label>
			                <?php echo $this->formText($form->get('cuentabancariamovimiento_cantidad')) ?>
		        		</div>

		        		<div class="form-group">
			           		<label  for="referencia">Referencia</label>
			                <?php echo $this->formText($form->get('cuentabancariamovimiento_referencia')) ?>
		        		</div>

		        		
		        	</div>
		        	<div class="col-md-1"></div>
	        		<div class="col-md-5">
		       			<div class="form-group">
			           		<label  for="Proveedor">Cuenta </label>
			                <?php echo $this->formSelect($form->get('idcuentabancaria')) ?>
		        		</div>

		        		<div class="form-group">
			           		<label  for="marca"> Medio de pago </label>
			                <?php echo $this->formSelect($form->get('cuentabancariamovimiento_medio')) ?>
		        		</div>

		        		<div class="form-group">
			           		<label  for="Temporada">Comprobante</label>
			                <?php echo $this->formFile($form->get('cuentabancariamovimiento_comprobante')) ?>
		        		</div>

		        		
		        	</div>
	        	
					</div> <!--end class row-->

					

	        	<div class="row">
	        		<div class="col-md-2 alineamiento " >
							<div class="">
			           		<label  for="guardar"></label>
		                    <button class="btn btn-primary btn-block btn-next " type="submit" id="guardarbtn">
	                         	Guardar
	                        </button>
	                    </div>
	                </div>
        		</div>
 
    			<br>
    			<br>
    			<div class="row">
		        		
    					<div class="col-md-11 alineamiento" >
    						
							

	        				<div id="medidasInformation">

	                            <table class="table table-bordered " id="tabla_movimientos">
		        				    <thead>
		        				      <tr>
		        				        <th>Fecha</th>
		        				        <th>Cuenta</th>
		        				        <th>Cantidad</th>
		        				        <th>Medio</th>
		        				        <th>Referencia</th>
		        				        <th>Comprobante</th>
		        				        <th>Opciones</th>
		        				      </tr>
		        				    </thead>
		        				    <tbody>
		        
		        				    </tbody>
		        				</table>
		        					
	        				</div>

	        			</div>	

		        	</div>
    		</div>
    	</div>
	</div>


	

   

</div>
<link rel="stylesheet"  href="/css/tableScroll.css">


<script src="/js/flujoefectivo/por_pagar_ver.js"></script>
<script>
	var por_pagar_ver = $('.body_container').por_pagar_ver();
	por_pagar_ver.initForm();

</script>

