<div class="body_container">
	<div class="title-bar">
	    <h1 class="title-bar-title">Créditos/apartados por vencer </h1>
	    <input type="text" id="btn_download" hidden="" disabled="">
	</div>
	<br>
	<br>

	<div class="row">
		<div class="col-md-8"></div>
		<div class="col-md-2 pull-right">
			<button id="btn_excel" class="btn btn-success"><span class="icon icon-file-excel-o"></span> EXCEL</button>

		</div>
	</div>

	<div class="row">
		<div class="col-md-3">
			<label class="col-sm-3 control-label" for="form-control-18">Desde</label>
			<?php echo $this->formDate($form->get('fecha_desde')) ?>
		</div>
		<div class="col-md-3">
			<label class="col-sm-3 control-label" for="form-control-18">Hasta</label>
			<?php echo $this->formDate($form->get('fecha_hasta')) ?>
		</div>
		<div class="col-md-3">
			<label class="col-sm-3 control-label" for="form-control-18">Vendedor</label>
			<?php echo $this->formSelect($form->get('idvendedor[]')) ?>
		</div>
		<div class="col-md-3">
			<label class="col-sm-3 control-label" for="form-control-18">Tipo</label>
			<?php echo $this->formSelect($form->get('idtipo[]')) ?>
		</div>
	</div>

	

	<div class="row">
		<div class="card-body">
		    <table id="" class="table table-striped table-nowrap dataTable" cellspacing="0" width="100%">
		        <thead>
		            <tr>
		                <th>Fecha compra</th>
		                <th>Fecha vencimiento</th>
		                <th>Tipo</th>
		                <th>Vendedor</th>
		                <th>Cliente</th>
		                <th>Folio</th>
		                <th>Adeudo</th>
		                <th>Total</th>
		            </tr>
		        </thead>
		        <tfoot>
		            <tr>
		                <th>Fecha compra</th>
		                <th>Fecha vencimiento</th>
		                <th>Tipo</th>
		                <th>Vendedor</th>
		                <th>Cliente</th>
		                <th>Folio</th>
		                <th>Adeudo</th>
		                <th>Total</th>
		            </tr>
		        </tfoot>
		        <tbody>
		            
		        </tbody>
		    </table>
		</div>
	</div>

</div>
<script src="/js/reporte/porPagar.js"></script>
<script>
	var porPagar = $('.body_container').porPagar();
	porPagar.list();
</script>
