<div class="body_container">
	<div class="title-bar">
	    <h1 class="title-bar-title">Proveedores - Agregar</h1>
	</div>
    <div class="row">
        <div class="col-md-offset-1 col-md-10">
    		<div class="demo-form-wrapper">
    			<form class="form form-horizontal" action="/catalogo/proveedores/nuevo" method="POST">
    				<div class="panel panel-info">
						<div class="panel-heading"><h4>INFORMACIÓN</h4></div>

						 <div class="panel-body">
			       			<div class="form-group">
				           		<label class="col-sm-3 control-label" for="form-control-18">Nombre</label>
				            	<div class="col-sm-8">
				                	<?php echo $this->formText($form->get('proveedor_nombrecomercial')) ?>
				            	</div>
			        		</div>

			        		<div class="form-group">
				           		<label class="col-sm-3 control-label" for="form-control-18">Teléfono</label>
				            	<div class="col-sm-8">
				                	<?php echo $this->formText($form->get('proveedor_telefono')) ?>
				            	</div>
			        		</div>

			        		<div class="form-group">
				           		<label class="col-sm-3 control-label" for="form-control-18">Celular</label>
				            	<div class="col-sm-8">
				                	<?php echo $this->formText($form->get('proveedor_celular')) ?>
				            	</div>
			        		</div>

			        		<div class="form-group">
				           		<label class="col-sm-3 control-label" for="form-control-18">Email</label>
				            	<div class="col-sm-8">
				                	<?php echo $this->formText($form->get('proveedor_email')) ?>
				            	</div>
			        		</div>

			        		<div class="form-group">
				           		<label class="col-sm-3 control-label" for="form-control-18">Fecha de inicio</label>
				            	<div class="col-sm-8">
				                	<?php echo $this->formText($form->get('proveedor_fechainicio')) ?>
				            	</div>
			        		</div>

			        		<div class="form-group">
				           		<label class="col-sm-3 control-label" for="form-control-18">Marcas</label>
				            	<div class="col-sm-8">
				                	<?php echo $this->formSelect($form->get('idmarca[]')) ?>
				           		</div>
			        		</div>
			        	</div>
			        </div>


                    

		        	<div class="form-group">
		           		<label  for="guardar"></label>
		                <button class="btn btn-primary btn-block btn-next" type="submit" tabindex="23">Guardar</button>
		    		</div>
 
    			</form>
                    
    		</div>
    	</div>
	</div>
</div>
<script src="/js/catalogo/proveedores.js"></script>
<script>
	var proveedores = $('.body_container').proveedores();
	proveedores.initForm();
</script>

<script type="text/javascript">
	$(document).ready(function() {
	  $('form').on('submit', function(e) {
	    $(this).find('button, input[type=button]').prop('disabled', true);
	  });
	});
</script>
