<div class="body_container">
	<div class="title-bar">
	    <h1 class="title-bar-title"><?php echo $entity->getProveedornombrecomercial() ?></h1>
	</div>
    <div class="row">
        <div class="col-md-8">
    		<div class="demo-form-wrapper">
    			<form class="form form-horizontal" action="/catalogo/proveedores/ver/<?php echo $entity->getidProveedor()?>" method="POST">
    			<input type="hidden" name="idproveedor" value="<?php echo $entity->getIdproveedor()?>">
	       			<div class="form-group">
		           		<label class="col-sm-3 control-label" for="form-control-18">Nombre</label>
		            	<div class="col-sm-9">
		                	<?php echo $this->formText($form->get('proveedor_nombrecomercial')) ?>
		            	</div>
	        		</div>

	        		<div class="form-group">
		           		<label class="col-sm-3 control-label" for="form-control-18">Teléfono</label>
		            	<div class="col-sm-9">
		                	<?php echo $this->formText($form->get('proveedor_telefono')) ?>
		            	</div>
	        		</div>

	        		<div class="form-group">
		           		<label class="col-sm-3 control-label" for="form-control-18">Celular</label>
		            	<div class="col-sm-9">
		                	<?php echo $this->formText($form->get('proveedor_celular')) ?>
		            	</div>
	        		</div>

	        		<div class="form-group">
		           		<label class="col-sm-3 control-label" for="form-control-18">Email</label>
		            	<div class="col-sm-9">
		                	<?php echo $this->formText($form->get('proveedor_email')) ?>
		            	</div>
	        		</div>

	        		<div class="form-group">
		           		<label class="col-sm-3 control-label" for="form-control-18">Fecha de inicio</label>
		            	<div class="col-sm-9">
		                	<?php echo $this->formText($form->get('proveedor_fechainicio')) ?>
		            	</div>
	        		</div>


                    <div class="form-group">
		           		<label class="col-sm-3 control-label" for="form-control-18">Marcas</label>
		            	<div class="col-sm-9">
		                	<?php echo $this->formSelect($form->get('idmarca[]')) ?>
		           		</div>
	        		</div>

		        	<div class="form-group">
		       			<label class="col-sm-3 control-label" for="form-control-18"></label>
		    			<div class="col-sm-9">
		        			<button class="btn btn-primary btn-block btn-next" type="submit">Guardar</button>
		    			</div>
		        	</div>
 
    			</form>
                    
    		</div>
    	</div>
	</div>
</div>
<script src="/js/catalogo/proveedores.js"></script>
<script>
	var proveedores = $('.body_container').proveedores();
	proveedores.initForm();
</script>
