<div class="body_container">
	<div class="title-bar">
	    <h1 class="title-bar-title">Cuentas por cobrar</h1>
	    
	</div>

	<?php foreach ($messages->getSuccessMessages() as $message):?>
	        <div class="alert alert-success alert-dismissable">
	            <button class="close" aria-hidden="true" data-dismiss="alert" type="button"></button>
	            <strong>Éxito!</strong>
	            <?php echo $message?>
	        </div>
	<?php endforeach;?>

	<?php foreach ($messages->geterrorMessages() as $message):?>
	        <div class="alert alert-danger alert-dismissable">
	            <button class="close" aria-hidden="true" data-dismiss="alert" type="button"></button>
	            <strong>Error!</strong>
	            <?php echo $message?>
	        </div>
	<?php endforeach;?>

	<div class="row">
		<div class="col-md-12">
			<a class="btn btn-bg btn-success btn-labeled pull-right" href="/compras/generales/nuevo">
              Nueva cuenta por cobrar
              <span class="btn-label btn-label-right">
                <span class="icon icon-plus-square icon-lg icon-fw"></span>
              </span>
            </a>
		</div>
	</div>

	<div class="row">
		<div class="card-body">
		    <table id="" class="table table-striped table-nowrap dataTable" cellspacing="0" width="100%">
		        <thead>
		            <tr>
		                <th>Proveedor</th>
		                <th>Folio</th>
		                <th>Fecha</th>
		                <th>Total</th>
		                <th>Pagada</th>
		                <th>Opciones</th>
		            </tr>
		        </thead>
		        <tfoot>
		            <tr>
		                <th>Proveedor</th>
		                <th>Folio</th>
		                <th>Fecha</th>
		                <th>Total</th>
		                <th>Pagada</th>
		                <th>Opciones</th>
		            </tr>
		        </tfoot>
		        <tbody>
		            
		        </tbody>
		    </table>
		</div>
	</div>

</div>
<script src="/js/fluejoefectivo/cuenta_por_cobrar.js"></script>

<script>
	var cuenta_por_cobrar = $('.body_container').cuenta_por_cobrar();
	cuenta_por_cobrar.list();
</script>
