<div class="login">
    <div class="login-body">
        <a class="login-brand" href="/">
            <img class="img-responsive" src="/img/logos/zaraly.jpeg" alt="Elephant">
        </a>
        <div class="login-form">
            <form data-toggle="validator" method="POST" action="/login/in">
                <div class="form-group">
                    <label for="email">Nombre de usuario</label>
                    <input id="email" class="form-control" type="text" name="username" spellcheck="false" autocomplete="off" data-msg-required="Please enter your username." required>
                </div>
                <div class="form-group">
                    <label for="password">Contraseña</label>
                    <input id="password" class="form-control" type="password" name="password" minlength="6" data-msg-minlength="Password must be 6 characters or more." data-msg-required="Please enter your password." required>
                </div>

                <button class="btn btn-primary btn-block" type="submit">Ingresar</button>
            </form>
        </div>
    </div>
</div>
