<div class="login">
    <div class="login-body">
        <a class="login-brand" href="index.html">
            <img class="img-responsive" src="/img/logos/zaraly.jpeg" alt="Elephant">
        </a>
        <div class="login-form">
            <form data-toggle="validator" method="POST" action="/login/select">
                <div class="form-group">
                    <label for="username" class="control-label">Sucursal</label>
                    <select name="idsucursal" class="form-control" >
                        <?php foreach ($sucursales as $key => $value) : ?>
                            <option value="<?php echo $key ?>"><?php echo $value ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>

                <button class="btn btn-primary btn-block" type="submit">Ingresar</button>
            </form>
        </div>
    </div>
</div>
