<div class="body_container">
	<div class="title-bar">
	    <h1 class="title-bar-title">Pedidos solicitados</h1>
	    
	</div>

	<?php foreach ($messages->getSuccessMessages() as $message):?>
	        <div class="alert alert-success alert-dismissable">
	            <button class="close" aria-hidden="true" data-dismiss="alert" type="button"></button>
	            <strong>Éxito!</strong>
	            <?php echo $message?>
	        </div>
	<?php endforeach;?>

	<?php foreach ($messages->geterrorMessages() as $message):?>
	        <div class="alert alert-danger alert-dismissable">
	            <button class="close" aria-hidden="true" data-dismiss="alert" type="button"></button>
	            <strong>Error!</strong>
	            <?php echo $message?>
	        </div>
	<?php endforeach;?>


	<div class="row">
		<div class="card-body">
		    <table id="" class="table table-striped table-nowrap dataTable" cellspacing="0" width="100%">
		        <thead>
		            <tr>
		                <th>ID</th>
		                <th>Modelo</th>
		                <th>Marca</th>
		                <th>Proveedor</th>
		                <th>Opciones</th>
		            </tr>
		        </thead>
		        <tfoot>
		            <tr>
		                <th>ID</th>
		                <th>Modelo</th>
		                <th>Marca</th>
		                <th>Proveedor</th>
		                <th>Opciones</th>
		            </tr>
		        </tfoot>
		        <tbody>
		            
		        </tbody>
		    </table>
		</div>
	</div>

</div>
<script src="/js/pedido/solicitado_producto.js"></script>

<script>
	var solicitado_producto = $('.body_container').solicitado_producto();
	solicitado_producto.list();
</script>
