<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>ZARELY - ADMINISTRADOR</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="apple-touch-icon" href="apple-touch-icon.png">
    <link rel="icon" href="favicon.ico">

    <link rel="stylesheet" href="/css/vendor.min.css">
    <link rel="stylesheet" href="/css/elephant.min.css">
    <link rel="stylesheet" href="/css/application.min.css">
    <link rel="stylesheet"  href="/css/custom.css">
    <link rel="stylesheet"  href="/plugins/MultipleSelect/multiple-select.css">
    <link rel="stylesheet"  href="/plugins/DatePicker/bootstrap-datepicker3.css">
    <link rel="stylesheet"  href="/css/newStyles.css">

    <script src="/js/vendor.min.js"></script>
    <script src="/js/elephant.min.js"></script>
    <script src="/plugins/MultipleSelect/multiple-select.js"></script>
    <script src="/plugins/DatePicker/bootstrap-datepicker.js"></script>
    <script src="/plugins/DatePicker/bootstrap-datepicker.es.js"></script>
    <script src="/plugins/Numeric/numeric.js"></script>
    <script src="/plugins/Accounting/accounting.js"></script>
  </head>
  <body class="layout">
    <?php $session = new \Application\Session\AouthSession();
      $session = $session->getData();
    ?>
    <div class="layout-header">
      <div class="navbar navbar-default" >
        <div class="navbar-header" style="background-color: #0288d1;">
          <a class="navbar-brand navbar-brand-center" href="/">ZARELY</a>
          <button class="navbar-toggler collapsed visible-xs-block" type="button" data-toggle="collapse" data-target="#sidenav">
            <span class="sr-only">Toggle navigation</span>
            <span class="bars">
              <span class="bar-line bar-line-1 out"></span>
              <span class="bar-line bar-line-2 out"></span>
              <span class="bar-line bar-line-3 out"></span>
            </span>
            <span class="bars bars-x">
              <span class="bar-line bar-line-4"></span>
              <span class="bar-line bar-line-5"></span>
            </span>
          </button>
          <button class="navbar-toggler collapsed visible-xs-block " type="button" data-toggle="collapse" data-target="#navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="arrow-up"></span>
            <span class="ellipsis ellipsis-vertical"></span>
          </button>
        </div>
        <div class="navbar-toggleable">
          <nav id="navbar" class="navbar-collapse collapse" style="background-color: #0288d1;">
            <button class="sidenav-toggler hidden-xs" style="background-color: #0288d1;"   title="Collapse sidenav ( [ )" type="button">
              <span class="sr-only">Toggle navigation</span>
              <span class="bars">
                <span class="bar-line bar-line-1 out" ></span>
                <span class="bar-line bar-line-2 out"></span>
                <span class="bar-line bar-line-3 out"></span>
                <span class="bar-line bar-line-4 in"></span>
                <span class="bar-line bar-line-5 in"></span>
                <span class="bar-line bar-line-6 in"></span>
              </span>
            </button>
            <ul class="nav navbar-nav navbar-right">
              <li class="visible-xs-block " >
                <h4 class="navbar-text text-center">Hi, Username</h4>
              </li>
              <li class="hidden-xs hidden-sm " style="border-left-width: 0px">
                <form class="navbar-search navbar-search-collapsed">
                  <div class="navbar-search-group">
                    <input class="navbar-search-input" type="text" placeholder="Search for people, companies, and more…">
                    <button class="navbar-search-toggler" title="Expand search form ( S )" type="button" style="background-color: #0288d1;" style="color:#fff">
                      <span class="icon icon-search icon-lg"></span>
                    </button>
                    <button class="navbar-search-adv-btn" type="button">Advanced</button>
                  </div>
                </form>
              </li>
              <li style="border-left-width: 0px;"><a href="#" style="color:#fff" >Link</a></li>
              <li style="border-left-width: 0px;"><a href="/" style="color:#fff"><?php echo $session["empleado_nombre"]?></a>
              </li>
              <li style="border-left-width: 0px;"> <a href="/login/out" style="color:#fff">Cerrar sesión</a></li>
            </ul>
          </nav>
        </div>
      </div>
    </div>
    <div class="layout-main" >
      <div class="layout-sidebar" >
        <div class="layout-sidebar-backdrop" style="background-color: #fff; border-right-width: 2px;border-right-style: solid; border-right-color:  #eee;"></div>
        <div class="layout-sidebar-body">
          <nav id="sidenav" class="sidenav-collapse collapse">
            <ul class="sidenav">
              <li class="sidenav-heading">Menu</li>
                <li class="sidenav-item has-subnav">
                  <a href="javascript:;" aria-haspopup="true">
                    <span class="sidenav-icon icon icon-book"></span>
                    <span class="sidenav-label">Catálogos</span>
                  </a>
                  <ul class="sidenav-subnav collapse" aria-expanded="false">
                    <li class="sidenav-subheading">Catálogos</li>
                    <li><a href="/catalogo/empleados" ><span class="icon icon-user" ></span>Empleados</a></li>
                    <li><a href="/catalogo/clientes" >Clientes</a></li>
                    <li><a href="/catalogo/proveedores" >Proveedores</a></li>
                    <li><a href="/catalogo/sucursales" >Sucursales</a></li>  
                    <li><a href="/catalogo/productos" >Productos</a></li>
                    <li><a href="/catalogo/temporadas" >Temporadas</a></li>
                    <li><a href="/catalogo/colores" >Colores</a></li>
                    <li><a href="/catalogo/materiales" >Materiales</a></li>
                    <li><a href="/catalogo/marcas" >Marcas</a></li>
                    <li><a href="/catalogo/tipocalzados" >Tipo de calzado o línea</a></li>
                    <li><a href="/catalogo/tallajes" >Tallajes</a></li>
                    <li><a href="/catalogo/medidas" >Medidas</a></li>


                    <li><a href="/catalogo/gastos" ><span class="icon icon-money"></span>Gastos</a></li>
                  </ul>

                </li>

                <li class="sidenav-item has-subnav">
                  <a href="javascript:;" aria-haspopup="true">
                    <span class="sidenav-icon icon icon-exchange"></span>
                    <span class="sidenav-label">Productos</span>
                  </a>
                  <ul class="sidenav-subnav collapse" aria-expanded="false">
                    <li class="sidenav-subheading">Productos</li>
                    
                    <li><a href="/producto/existencias">Existencia</a></li>
                    <li><a href="/producto/reordenes">Reorden</a></li>
                    <li><a href="/producto/precios">Precios</a></li>   
                    <li><a href="/producto/enreorden">Productos en reorden</a></li>     
                  </ul>

                </li>

                <li class="sidenav-item has-subnav">
                  <a href="javascript:;" aria-haspopup="true">
                    <span class="sidenav-icon icon icon-bus"></span>
                    <span class="sidenav-label">Pedidos</span>
                  </a>
                  <ul class="sidenav-subnav collapse" aria-expanded="false">
                    <li class="sidenav-subheading">Pedidos</li>
                    <li><a href="/pedidos/mayoristas" >Mayoristas</a></li>
                    <li><a href="/pedidos/completados">Completados por sucursal</a></li>
                    <li><a href="/pedidos/completados-producto">Completados por producto</a></li>

                    <li><a href="/pedidos/pendientes">Pendientes por sucursal</a></li>
                    <li><a href="/pedidos/pendientes-producto">Pendientes por producto</a></li>

                    <li><a href="/pedidos/solicitados">Solicitados por sucursal</a></li>
                    <li><a href="/pedidos/solicitados-producto">Solicitados por producto</a></li>
                    
                    <li><a href="/pedidos/transitos">Tránsito por sucursal</a></li>
                    <li><a href="/pedidos/transitos-producto">Tránsito por producto</a></li>
                        
                  </ul>

                </li>


                <li class="sidenav-item has-subnav">
                  <a href="javascript:;" aria-haspopup="true">
                    <span class="sidenav-icon icon icon-exchange"></span>
                    <span class="sidenav-label">Compras</span>
                  </a>
                  <ul class="sidenav-subnav collapse" aria-expanded="false">
                    <li class="sidenav-subheading">Compras</li>
                    
                    <li><a href="/compras/generales">Generales</a></li>   
                  </ul>

                </li>


            </ul>
          </nav>
        </div>
      </div>
      <div class="layout-content">
        <div class="layout-content-body" >
          <?php echo $this->content?>
        </div>
      </div>
      <!-- 
      <div class="layout-footer">
        <div class="layout-footer-body">
          
        </div>
      </div>
        -->
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>

    </div>
    
  </body>
    <script src="/js/application.min.js"></script>
    

</html>