<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>ZARELY - ADMINISTRADOR</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="apple-touch-icon" href="apple-touch-icon.png">
    <link rel="icon" href="favicon.ico">

    <link rel="stylesheet" href="/css/vendor.min.css">
    <link rel="stylesheet" href="/css/elephant.min.css">
    <link rel="stylesheet" href="/css/application.min.css">
    <link rel="stylesheet"  href="/css/custom.css">
    <script src="/js/vendor.min.js"></script>


  </head>
  <body class="layout">
    <div class="layout-header">
      <div class="navbar navbar-default">
        <div class="navbar-header">
          <a class="navbar-brand navbar-brand-center" href="/">ZARELY</a>
          <button class="navbar-toggler collapsed visible-xs-block" type="button" data-toggle="collapse" data-target="#sidenav">
            <span class="sr-only">Toggle navigation</span>
            <span class="bars">
              <span class="bar-line bar-line-1 out"></span>
              <span class="bar-line bar-line-2 out"></span>
              <span class="bar-line bar-line-3 out"></span>
            </span>
            <span class="bars bars-x">
              <span class="bar-line bar-line-4"></span>
              <span class="bar-line bar-line-5"></span>
            </span>
          </button>
          <button class="navbar-toggler collapsed visible-xs-block" type="button" data-toggle="collapse" data-target="#navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="arrow-up"></span>
            <span class="ellipsis ellipsis-vertical"></span>
          </button>
        </div>
        <div class="navbar-toggleable">
          <nav id="navbar" class="navbar-collapse collapse">
            <button class="sidenav-toggler hidden-xs" title="Collapse sidenav ( [ )" type="button">
              <span class="sr-only">Toggle navigation</span>
              <span class="bars">
                <span class="bar-line bar-line-1 out"></span>
                <span class="bar-line bar-line-2 out"></span>
                <span class="bar-line bar-line-3 out"></span>
                <span class="bar-line bar-line-4 in"></span>
                <span class="bar-line bar-line-5 in"></span>
                <span class="bar-line bar-line-6 in"></span>
              </span>
            </button>
            <ul class="nav navbar-nav navbar-right">
              <li class="visible-xs-block">
                <h4 class="navbar-text text-center">Hi, Username</h4>
              </li>
              <li class="hidden-xs hidden-sm">
                <form class="navbar-search navbar-search-collapsed">
                  <div class="navbar-search-group">
                    <input class="navbar-search-input" type="text" placeholder="Search for people, companies, and more…">
                    <button class="navbar-search-toggler" title="Expand search form ( S )" type="button">
                      <span class="icon icon-search icon-lg"></span>
                    </button>
                    <button class="navbar-search-adv-btn" type="button">Advanced</button>
                  </div>
                </form>
              </li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
            </ul>
          </nav>
        </div>
      </div>
    </div>
    <div class="layout-main">
      <div class="layout-sidebar">
        <div class="layout-sidebar-backdrop"></div>
        <div class="layout-sidebar-body">
          <nav id="sidenav" class="sidenav-collapse collapse">
            <ul class="sidenav">
              <li class="sidenav-heading">Menu</li>
              <li class="sidenav-item has-subnav">
                  <a href="javascript:;" aria-haspopup="true">
                    <span class="sidenav-icon icon icon-book"></span>
                    <span class="sidenav-label">Catalogos</span>
                  </a>
                  <ul class="sidenav-subnav collapse" aria-expanded="false">
                    <li class="sidenav-subheading">Catalogos</li>
                    <li><a href="/catalogo/materiales">Materiales</a></li>
                    <li><a href="/catalogo/marcas">Marcas</a></li>
                    <li><a href="dashboard-3.html">Colores</a></li>
                  </ul>
                </li>
            </ul>
          </nav>
        </div>
      </div>
      <div class="layout-content">
        <div class="layout-content-body">
          <?php echo $this->content?>
        </div>
      </div>
      <div class="layout-footer">
        <div class="layout-footer-body">
          <small>Thank you for creating with <a href="http://demo.naksoid.com/elephant/">Elephant Template</a>.</small>
        </div>
      </div>
        
        <script src="/js/elephant.min.js"></script>
        <script src="/js/application.min.js"></script>

    </div>
    
  </body>
    <script src="/js/application.min.js"></script>
    <script src="/js/elephant.min.js"></script>

</html>