<div class="body_container">
	<div class="title-bar">
	</div>
    <div class="row">
        <div class="col-md-offset-1 col-md-10">
    		<div class="demo-form-wrapper">
    			<form class="form form-horizontal" action="/catalogo/marcas/nuevo" method="POST">


    				<div class="panel panel-info">
						<div class="panel-heading"><h4>Nueva marca</h4></div>

						 <div class="panel-body">
			       			<div class="form-group">
				           		<label class="col-sm-3 control-label" for="form-control-18">Nombre</label>
				            	<div class="col-sm-9">
				                	<?php echo $this->formText($form->get('marca_nombre')) ?>
				            	</div>
			        		</div>
		                    <div class="form-group">
				           		<label class="col-sm-3 control-label" for="form-control-18">Tallaje</label>
				            	<div class="col-sm-9">
				                	<?php echo $this->formSelect($form->get('idtallaje[]')) ?>
				            	</div>
			        		</div>
			        	</div>
			        </div>


                    

		        	<div class="form-group">
		           		<label  for="guardar"></label>
		                <button class="btn btn-primary btn-block btn-next" type="submit" tabindex="23">Guardar</button>
		    		</div>


	       			
		        	
    			</form>
                    
    		</div>
    	</div>
	</div>
</div>
<script src="/js/catalogo/marcas.js"></script>
<script>
	var marcas = $('.body_container').marcas();
	marcas.initForm();
</script>

<script type="text/javascript">
	$(document).ready(function() {
	  $('form').on('submit', function(e) {
	    $(this).find('button, input[type=button]').prop('disabled', true);
	  });
	});
</script>
