<div class="body_container">
	<div class="title-bar">
	    <h1 class="title-bar-title">Marcas - Agregar</h1>
	</div>
    <div class="row">
        <div class="col-md-8">
    		<div class="demo-form-wrapper">
    			<form class="form form-horizontal" action="/catalogo/marcas/nuevo" method="POST">
	       			<div class="form-group">
		           		<label class="col-sm-3 control-label" for="form-control-18">Nombre</label>
		            	<div class="col-sm-9">
		                	<?php echo $this->formText($form->get('marca_nombre')) ?>
		            	</div>
	        		</div>
                    <div class="form-group">
		           		<label class="col-sm-3 control-label" for="form-control-18">Tallaje</label>
		            	<div class="col-sm-9">
		                	<?php echo $this->formSelect($form->get('idtallaje[]')) ?>
		            	</div>
	        		</div>
		        	<div class="form-group">
		       			<label class="col-sm-3 control-label" for="form-control-18"></label>
		    			<div class="col-sm-9">
		        			<button class="btn btn-primary btn-block btn-next" type="submit">Guardar</button>
		    			</div>
		        	</div>
 
    			</form>
                    
    		</div>
    	</div>
	</div>
</div>
<script src="/js/catalogo/marcas.js"></script>
<script>
	var marcas = $('.body_container').marcas();
	marcas.initForm();
</script>

<script type="text/javascript">
	$(document).ready(function() {
	  $('form').on('submit', function(e) {
	    $(this).find('button, input[type=button]').prop('disabled', true);
	  });
	});
</script>
