<div class="body_container">
	<div class="title-bar">
	    <h1 class="title-bar-title"> Defectos de la venta <?php echo $entity->getIdventa() ?> </h1>
	</div>
    <div class="row">
        <div class="col-md-offset-1 col-md-10">
    		<div class="demo-form-wrapper">
    			<form class="form form-horizontal" name="formulario" action="/puntodeventa/devoluciones/<?php echo $entity->getIdventa() ?>" method="POST" id="venta_devolucion" enctype="multipart/form-data"" >
    				<input type="hidden" name="idventa" value="<?php echo $entity->getIdventa()?>">

                    <div class="row">
                        <div class="col-md-5">
                            <div class="form-group">
                                <label  for="fecha">Fecha </label>
                                <?php echo $this->formText($form->get('venta_fecha')) ?>
                            </div>

                            <div class="form-group">
                                <label  for="cajero"> Cajero</label>
                                <?php echo $this->formText($form->get('idempleadocajero')) ?>
                            </div>

                            <div class="form-group">
                                <label  for="vendedor">Vendedor</label>
                                <?php echo $this->formText($form->get('idempleadovendedor')) ?>
                            </div>

                            <div class="form-group">
                                    <label  for="cliente">Cliente</label>
                                    <div id="clientes_select">
                                        <?php echo $this->formText($form->get('idcliente')) ?>
                                    </div>
                            </div>

                        </div>
                        <div class="col-md-1"></div>
                        <div class="col-md-5">
                            <div class="form-group">
                                <label  for="folio">Folio </label>
                                <?php echo $this->formText($form->get('folio')) ?>
                            </div>

                            <div class="form-group">
                                <label  for="tipo"> Tipo </label>
                                <?php echo $this->formText($form->get('venta_tipo')) ?>
                            </div>

                            <div class="form-group">
                                <label  for="pago">Pago</label>
                                <?php echo $this->formText($form->get('venta_estatuspago')) ?>
                            </div>

                            <div class="form-group">
                                <label  for="estatus">Estatus</label>
                                <?php echo $this->formSelect($form->get('venta_estatus')) ?>
                            </div>

                            
                        </div>
                    
                    </div> 
                    <div class="row">
                        <div class="col-md-11 alineamiento">
                            <h1>Defectos a devolver</h1>
                            <div class="row">
                                <div class="col-md-12" >
                                    <table class="table table-bordered" id="productos">
                                        <thead>
                                            <tr>
                                                <th>Defectos</th>
                                                <th>Total</th>
                                                <th>Cantidad a devolver</th>
                                                <th>Nombre del producto</th>
                                            </tr>
                                            
                                        </thead>

                                        <tbody id="tables_information">
                                            
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row">

                        <div class="col-md-11 alineamiento" >
                            <h1>Nuevos productos</h1>
                            <div id="medidasInformation">
                                <div id="variantes">
                                    <div class="col-md-9 ">
                                        <div class="form-group">
                                            <?php echo $this->formSelect($form->get('idproductovariante1[]')) ?>
                                        </div>
                                    </div>
                                    <div class="col-md-1 "></div>

                                    <div class="col-md-2 ">     
                                        <div class="form-group" style="margin-top: -23px">
                                            <label  for="guardar"></label>
                                            <a class="btn btn-primary btn-block btn-next" id="btn_add_productovariante1">           Agregar
                                            </a>
                                        </div>
                                    </div>  
                                </div>

                                

                                <div class="row">
                                    <div class="col-md-12" >
                                        <table class="table table-bordered" id="table_venta1">
                                            <thead>
                                                <tr>
                                                    <th>Cantidad</th>
                                                    <th>Nombre del producto</th>
                                                    <th>Descripción</th>
                                                    <th>Precio unitario</th>
                                                    <th>Descuento</th>
                                                    <th>Subtotal</th>
                                                    <th>Opciones</th>
                                                </tr>
                                                
                                            </thead>

                                            <tbody id="tables_information1">
                                                
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                                <div id="informacion_venta1">
                                    <div class="row">
                                        <div class="col-md-12">
                                            <label  class="pull-right" >
                                              SUBTOTAL:
                                                <input id="total_transferencia1" type="text" name="transferencia_subtotal1" disabled>
                                              
                                              </span>
                                            </label>
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="col-md-12">
                                            <label  class="pull-right" >
                                              IVA:
                                                <input id="total_transferencia1" type="text" name="transferencia_iva1"  disabled>
                                              
                                              </span>
                                            </label>
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="col-md-12">
                                            <label  class="pull-right" >
                                              TOTAL:
                                                <input id="total_transferencia1" type="text" name="transferencia_total1" disabled>
                                              
                                              </span>
                                            </label>
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="col-md-12">
                                        <input type="hidden" name="venta_total" value="<?php echo $entity->getVentaTotal()?>">
                                            <label  class="pull-right" >
                                              SALDO RESTANTE:
                                                <input id="diferencia_venta" type="text" value="$0.0" name="diferencia_venta" disabled>
                                              
                                              </span>
                                            </label>
                                        </div>
                                    </div>
                                </div>
                                <br>
                                <br>
                            
                            </div>

                        </div>  
                    </div>
                    

		        	<div class="row">
		        		<div class="col-md-11 alineamiento" >
 							<div class="form-group" style="margin-top: -23px">
				           		<label  for="guardar"></label>
                                <button type="button" class="btn btn-primary btn-block btn-next" id="terminar_venta">			Pagar
                                </button>
			        		</div>
		                </div>
	        		</div>
 
    			</form>
    		</div>
    	</div>
	</div>


	

   

</div>
<link rel="stylesheet"  href="/css/tableScroll.css">
<script type="text/javascript" src="https://cdn.jsdelivr.net/sweetalert2/6.4.2/sweetalert2.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/sweetalert2/6.4.2/sweetalert2.min.css">

<script src="/js/puntodeventa/defectos.js"></script>
<script>
	var defectos = $('.body_container').defectos();
	defectos.initForm();
</script>

