<div class="body_container">
	<div class="title-bar">
	    <h1 class="title-bar-title"> Punto de venta - Editar </h1>
	</div>
    <div class="row">
        <div class="col-md-offset-1 col-md-10">
    		<div class="demo-form-wrapper">
    			<form class="form form-horizontal" name="formulario" action="/puntodeventa/ver/<?php echo $entity->getIdventa() ?>" method="POST" enctype="multipart/form-data"">
    				<input type="hidden" name="idventa" value="<?php echo $entity->getIdventa()?>">

        			<div class="row">
		    			<div class="col-md-5">
			       			<div class="form-group">
				           		<label  for="fecha">Fecha </label>
				                <?php echo $this->formText($form->get('venta_fecha')) ?>
			        		</div>

			        		<div class="form-group">
				           		<label  for="cajero"> Cajero</label>
				                <?php echo $this->formText($form->get('idempleadocajero')) ?>
			        		</div>

			        		<div class="form-group">
				           		<label  for="vendedor">Vendedor</label>
				                <?php echo $this->formText($form->get('idempleadovendedor')) ?>
			        		</div>

			        		<div class="form-group">
					           		<label  for="cliente">Cliente</label>
					           		<div id="clientes_select">
					                	<?php echo $this->formText($form->get('idcliente')) ?>
				        			</div>
			        		</div>

			        	</div>
			        	<div class="col-md-1"></div>
		        		<div class="col-md-5">
			       			<div class="form-group">
				           		<label  for="folio">Folio </label>
				                <?php echo $this->formText($form->get('folio')) ?>
			        		</div>

			        		<div class="form-group">
				           		<label  for="tipo"> Tipo </label>
				                <?php echo $this->formText($form->get('venta_tipo')) ?>
			        		</div>

			        		<div class="form-group">
				           		<label  for="pago">Pago</label>
				                <?php echo $this->formText($form->get('venta_estatuspago')) ?>
			        		</div>

			        		<div class="form-group">
				           		<label  for="estatus">Estatus</label>
				                <?php echo $this->formSelect($form->get('venta_estatus')) ?>
			        		</div>

			        		
			        	</div>
		        	
 					</div> <!--end class row-->
 					<br><br>
      				<div class="row">

      					<div class="col-md-11 alineamiento" >

	        				<div id="medidasInformation">	        	

	                            <div class="row">
		                            <div class="col-md-12" >
		                            	<table class="table table-bordered" id="table_venta1">
		                            		<thead>
			                            		<tr>
			                            			<th>Cantidad</th>
			                            			<th>Nombre del producto</th>
			                            			<th>Descripción</th>
			                            			<th>Precio unitario</th>
			                            			<th>Descuento</th>
			                            			<th>Subtotal</th>
			                            		</tr>
		                            			
		                            		</thead>

		                            		<tbody id="tables_information1">
		                            			
		                            		</tbody>
		                            	</table>
		                            </div>
	                            </div>
	                            	<div id="informacion_venta1">
			        					<div class="row">
			        						<div class="col-md-12">
			        							<label  class="pull-right" >
			        				              SUBTOTAL:
			        				              	<input id="subtotal_transferencia" type="text" name="transferencia_subtotal" disabled>
			        				              
			        				              </span>
			        				            </label>
			        						</div>
			        					</div>

			        					<div class="row">
			        						<div class="col-md-12">
			        							<label  class="pull-right" >
			        				              IVA:
			        				              	<input id="iva_transferencia" type="text" name="transferencia_iva"  disabled>
			        				              
			        				              </span>
			        				            </label>
			        						</div>
			        					</div>

			        					<div class="row">
			        						<div class="col-md-12">
			        							<label  class="pull-right" >
			        				              TOTAL:
			        				              	<input id="total_transferencia" type="text" name="transferencia_total" disabled>
			        				              
			        				              </span>
			        				            </label>
			        						</div>
			        					</div>
		        					</div>
		        					<br>
		        					<br>
		        			
	        				</div>

	        			</div>	
      				</div>
		        	<div class="row">
		        		<div class="col-md-11 alineamiento" >
 							<div class="form-group" style="margin-top: -23px">
				           		<label  for="guardar"></label>
                                <button class="btn btn-primary btn-block btn-next" id="btn_venta_1">			Guardar
                                </button>
			        		</div>
		                </div>
	        		</div>
 
    			</form>
    		</div>
    	</div>
	</div>


	

   

</div>
<link rel="stylesheet"  href="/css/tableScroll.css">

<link rel="stylesheet"  href="/plugins/Select2/select2.min.css">
<script src="/plugins/Select2/select2.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/sweetalert2/6.4.2/sweetalert2.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/sweetalert2/6.4.2/sweetalert2.min.css">

<script src="/js/transferencia/ver.js"></script>
<script>
	var ver = $('.body_container').ver();
	ver.initForm();
</script>

