<div class="body_container">
	<div class="title-bar">
	    <h1 class="title-bar-title"></h1>
	</div>
    <div class="row">
        <div class="col-md-offset-1 col-md-10">
    		<div class="demo-form-wrapper">
    			<form class="form form-horizontal" action="/catalogo/gastos/ver/<?php echo $entity->getIdgasto() ?>" method="POST">
	       			<div class="panel panel-info">
						<div class="panel-heading"><h4>Editando gasto:  <?php echo $entity->getGastoNombre() ?></h4></div>

						 <div class="panel-body">
			       			<div class="form-group">
				           		<label class="col-sm-3 control-label" for="form-control-18">Nombre</label>
				            	<div class="col-sm-8">
				                	<?php echo $this->formText($form->get('gasto_nombre')) ?>
				            	</div>
			        		</div>

			        		<div class="form-group">
				           		<label class="col-sm-3 control-label" for="form-control-18">Descripción</label>
				            	<div class="col-sm-8">
				                	<?php echo $this->formTextarea($form->get('gasto_descripcion')) ?>
				            	</div>
			        		</div>
			        	</div>
			        </div>


                    

		        	<div class="form-group">
		           		<label  for="guardar"></label>
		                <button class="btn btn-primary btn-block btn-next" type="submit" tabindex="23">Guardar</button>
		    		</div>
 
    			</form>
    		</div>
    	</div>
	</div>
</div>
