
<link rel="stylesheet" href="/css/elephant.min.css">
<script src="/js/vendor.min.js"></script>
   

<div class="body_container">
	<div class="title-bar">

	    <div class="container">
	    	<br>
		    <?php foreach ($data as $sucursalInfo):?>
		    	<h3 style="margin-left: auto; margin-right: auto;width: 8em"><?php echo \SucursalQuery::create()->findPk($sucursalInfo['idsucursal'])->getSucursalNombrecomercial() ; ?></h3>
		    	<div class="row">
			    	
		            <?php for(  $i = 0; $i < $sucursalInfo['quantity']; $i++){?>
		            	<div class="col-sm-4" style="margin-top: 30px;">
		            		<?php echo $barcode; ?>
		            	</div>
	            	<?php }?>
	            </div>
	        	<br><br>
		    <?php endforeach;?>
		</div>

    	<label  for="guardar"></label>
        <button id="imprimir" class="btn btn-primary  btn-next">Guardar</button>
	</div>
</div>


<script type="text/javascript">
	$('#imprimir').on('click',function(){
      	window.print();
	});
</script>