<div class="body_container">
	<div class="title-bar">
	    <h1 class="title-bar-title">Etiquetas</h1>
	    
	</div>

	<?php foreach ($messages->getSuccessMessages() as $message):?>
	        <div class="alert alert-success alert-dismissable">
	            <button class="close" aria-hidden="true" data-dismiss="alert" type="button"></button>
	            <strong>Éxito!</strong>
	            <?php echo $message?>
	        </div>
	<?php endforeach;?>

	<?php foreach ($messages->geterrorMessages() as $message):?>
	        <div class="alert alert-danger alert-dismissable">
	            <button class="close" aria-hidden="true" data-dismiss="alert" type="button"></button>
	            <strong>Error!</strong>
	            <?php echo $message?>
	        </div>
	<?php endforeach;?>


	<div class="row">
		<div class="col-md-12">
			<button class="btn btn-bg btn-success btn-labeled pull-right" >
              Generar etiqueta
              <span class="btn-label btn-label-right">
                <span class="icon icon-plus-square icon-lg icon-fw"></span>
              </span>
            </button>
		</div>
	</div>

	<div class="row">
		<div class="card-body">
			<input type="hidden" name="idproducto" value="<?php echo $id ?>">
		    <table id="" class="table table-striped table-nowrap dataTable" cellspacing="0" width="100%">
		        <thead>
		            <tr>
		                <th>Código</th>
		                <th>Modelo</th>
		                <th>Talla</th>
		                <th>Marca</th>
		                <th>Color</th>
		                <th>Material</th>
		                <?php foreach($sucursales as $sucursal) :?>
		               		<th><?php echo $sucursal->getSucursalNombrecomercial()?></th> 	
		              	<?php endforeach;?>  	
		                <th>Generar etiqueta</th>
		            </tr>
		        </thead>
		        <tfoot>
		            <tr>
		                <th>Código</th>
		                <th>Modelo</th>
		                <th>Talla</th>
		                <th>Marca</th>
		                <th>Color</th>
		                <th>Material</th>
		                <?php foreach($sucursales as $sucursal) :?>
		               		<th><?php echo $sucursal->getSucursalNombrecomercial()?></th> 	
		              	<?php endforeach;?>  	
		                <th>Generar etiqueta</th>
		    
		            </tr>
		        </tfoot>
		        <tbody>
		            
		        </tbody>
		    </table>
		</div>
	</div>

</div>
<script type="text/javascript" src="https://cdn.jsdelivr.net/sweetalert2/6.4.2/sweetalert2.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/sweetalert2/6.4.2/sweetalert2.min.css">
<script src="/js/producto/codigodebarras.js"></script>

<script>
	var codigodebarras = $('.body_container').codigodebarras();
	codigodebarras.list(<?php echo $id ?>);
</script>
