<div class="body_container">
	<div class="title-bar">
	    <h1 class="title-bar-title"> Transferencia - Registro </h1>
	</div>
    <div class="row">
        <div class="col-md-offset-1 col-md-10">
    		<div class="demo-form-wrapper">
    			<form class="form form-horizontal" name="formulario" action="/transferencias-sucursal/nueva" method="POST" enctype="multipart/form-data"">
    				<div class="row">
		    			<div class="col-md-5">
			       			<div class="form-group">
				           		<label  for="Modelo">Fecha de transferencia</label>
				                <?php echo $this->formText($form->get('transferencia_fecha')) ?>
			        		</div>

			        		<div class="form-group">
				           		<label  for="dirigido"> Sucursal de origen</label>
				                <?php echo $this->formSelect($form->get('idsucursalorigen')) ?>
			        		</div>

			        		<div class="form-group">
				           		<label  for="tipo">Creador</label>
				                <?php echo $this->formText($form->get('idempleadocreador')) ?>
			        		</div>
			        		
			        		<div class="form-group">
				           		<label  for="Modelo">Fecha de recepción</label>
				                <?php echo $this->formText($form->get('transferencia_fecharecepcion')) ?>
			        		</div>

			        	</div>
			        	<div class="col-md-1"></div>
		        		<div class="col-md-5">
			       			<div class="form-group">
				           		<label  for="Proveedor">Estatus </label>
				                <?php echo $this->formSelect($form->get('transferencia_estatus')) ?>
			        		</div>


			        		<div class="form-group">
				           		<label  for="Proveedor">Sucursal de destino </label>
				                <?php echo $this->formSelect($form->get('idsucursaldestino')) ?>
			        		</div>

			        		<div class="form-group">
				           		<label  for="tipo">Receptor</label>
				                <?php echo $this->formSelect($form->get('idempleadoreceptor')) ?>
			        		</div>

			        		
			        	</div>
		        	
 					</div> <!--end class row-->


 					<div class="row">
		        		
    					<div class="col-md-11 alineamiento" >
    						
							<div class="form-group" >
								<label for="tallaje">Productos</label>
								
								<input type="radio" id="variante" name="validar" checked><label class="alinearTexto">Variante</label>
								<input type="radio" id="general" name="validar"><label class="alinearTexto">Producto general</label>
							</div>

	        				<div id="medidasInformation">
	        					<div id="variantes">
			        				<div class="col-md-9 ">
					                    <div class="form-group">
							                <?php echo $this->formSelect($form->get('idproductovariante[]')) ?>
						        		</div>
			        				</div>
			        				<div class="col-md-1 "></div>

					        		<div class="col-md-2 ">		
					        			<div class="form-group" style="margin-top: -23px">
							           		<label  for="guardar"></label>
		                                    <a class="btn btn-primary btn-block btn-next" id="btn_add_productovariante">			Agregar
		                                    </a>
						        		</div>
						        	</div>	
					        	</div>

					        	<div class="ocultar" id="producto_general"> 
					        		<div class="col-md-9 ">
					                    <div class="form-group">
							                <?php echo $this->formSelect($form->get('productos_generales')) ?>
						        		</div>
			        				</div>

			        				<div class="col-md-1 "></div>

					        		<div class="col-md-2 ">		
					        			<div class="form-group" style="margin-top: -23px">
							           		<label  for="guardar"></label>
		                                    <a class="btn btn-primary btn-block btn-next" id="btn_add_productogeneral">			Agregar
		                                    </a>
						        		</div>
						        	</div>
					        	</div>

	                            <div class="row">
		                            <div class="col-md-12" id="tables_information">
		                            	
		                            </div>
	                            </div>
		        					<div class="row">
		        						<div class="col-md-12">
		        							<label  class="pull-right" >
		        				              TOTAL:
		        				              	<input id="total_transferencia" type="text" name="transferencia_total" disabled>
		        				              
		        				              </span>
		        				            </label>
		        						</div>
		        					</div>
	        				</div>

	        			</div>	

		        	</div>
		        	<hr>

		        	
 					<div class="row">
 						<div class="col-md-11 alineamiento" >
 							<div class="">
				           		<label  for="nota">Notas</label>
				                <?php echo $this->formTextarea($form->get('transferencia_nota')) ?>
			        		</div>
 						</div>
 					</div>

		        	<div class="row">
		        		<div class="col-md-11 alineamiento" >
 							<div class="">
				           		<label  for="guardar"></label>
			                    <button class="btn btn-primary btn-block btn-next" type="submit">
		                         	Guardar
		                        </button>
		                    </div>
		                </div>
	        		</div>
 
    			</form>
    		</div>
    	</div>
	</div>


	

   

</div>
<link rel="stylesheet"  href="/css/tableScroll.css">

<link rel="stylesheet"  href="/plugins/Select2/select2.min.css">
<script src="/plugins/Select2/select2.min.js"></script>

<script src="/js/transferencia/generalessucursal.js"></script>
<script>
	var generalessucursal = $('.body_container').generalessucursal();
	generalessucursal.initForm();
</script>
<script type="text/javascript">
	$(document).ready(function() {
	  $('form').on('submit', function(e) {
	    $(this).find('button, input[type=button]').prop('disabled', true);
	  });
	});
</script>

