<div class="body_container">
	<div class="title-bar">
	    <h1 class="title-bar-title"></h1>
	</div>
    <div class="row">
        <div class="col-md-offset-1 col-md-10">
    		<div class="demo-form-wrapper">
    			<form class="form form-horizontal" action="/catalogo/cuentas/ver/<?php echo $entity->getIdcuentabancaria() ?>" method="POST">
	    			<div class="panel panel-info">
						<div class="panel-heading"><h4>Modificar cuenta: <?php echo $entity->getCuentabancariaCuenta() ?></h4></div>

						 <div class="panel-body">
		          			<div class="col-xs-5">
		      	       			
		      	        		<div class="form-group">
					           		<label  for="banco">Banco</label>
					                <?php echo $this->formText($form->get('cuentabancaria_banco')) ?>
				        		</div>

				        		
				        		<div class="form-group">
					           		<label  for="saldo">Saldo</label>
					                <?php echo $this->formText($form->get('cuentabancaria_saldo')) ?>
				        		</div>


		      	        	</div>

		      	        	<div class="col-xs-1"></div>

		      	        	<div class="col-xs-5">
	   			       			<div class="form-group">
					           		<label  for="cuenta">Cuenta</label>
					                <?php echo $this->formText($form->get('cuentabancaria_cuenta')) ?>
				        		</div>
		      	        	</div>
						</div>
					</div>
	    	
		     

		        	<div class="form-group">
		           		<label  for="guardar"></label>
		                <button class="btn btn-primary btn-block btn-next" type="submit" tabindex="4">Guardar</button>
	        		</div>
	       			<input type="hidden" name="idmarca" value="<?php echo $entity->getCuentabancariaCuenta()?>">


 
    			</form>
    		</div>
    	</div>
	</div>
</div>
<script src="/js/catalogo/cuentas.js"></script>
<script>
	var cuentas = $('.body_container').cuentas();
	cuentas.initForm();
</script>
