<div class="body_container">
	<div class="title-bar">
	    <h1 class="title-bar-title">Bajas existencias</h1>
	    <input type="text" id="btn_download" hidden="" disabled="">
	</div>
	<br>
	<br>

	<div class="row">
		<div class="col-md-8"></div>
		<div class="col-md-2 pull-right">
			<button id="btn_excel" class="btn btn-success"><span class="icon icon-file-excel-o"></span> EXCEL</button>

		</div>
	</div>

	<div class="row">

		<div class="col-md-4">
			<label class="col-sm-3 control-label" for="form-control-18">Marca</label>
			<?php echo $this->formSelect($form->get('idmarca[]')) ?>
		</div>
	</div>

	

	<div class="row">
		<div class="card-body">
		    <table id="" class="table table-striped table-nowrap dataTable" cellspacing="0" width="100%">
		        <thead>
		            <tr>
		                <th>Producto</th>
		                <th>Marca</th>
		                <th>Existencias</th>
		                <th>Mínima</th>
		                <th>Reorden</th>
		            </tr>
		        </thead>
		        <tfoot>
		            <tr>
		                <th>Producto</th>
		                <th>Marca</th>
		                <th>Existencias</th>
		                <th>Mínima</th>
		                <th>Reorden</th>
		            </tr>
		        </tfoot>
		        <tbody>
		            
		        </tbody>
		    </table>
		</div>
	</div>

</div>
<script src="/js/reporte/bajasexistencias.js"></script>
<script>
	var bajasexistencias = $('.body_container').bajasexistencias();
	bajasexistencias.list();
</script>
