
<div class="title-bar">
    <h1 class="title-bar-title">Bienvenido <?php echo  $session['empleado_nombre']."(".$session['rol_nombre'].")"?></h1>
    <h4>Dashboard</h4>
    <p class="title-bar-description">
    </p>
</div>

<div class="row gutter-xs">
    <div class="col-md-6 col-lg-3 col-lg-push-3">
    </div>

    <div class="col-md-6 col-lg-3 col-lg-push-3">
      <div class="card">
        <div class="card-body">
          <div class="media">
            <div class="media-middle media-left">
              <span class="bg-danger circle sq-48">
                <span class="icon icon-shopping-bag"></span>
              </span>
            </div>
            <div class="media-middle media-body">
              <h6 class="media-heading">Órdenes</h6>
              <h3 class="media-heading">
                <span class="fw-l"><?php echo $pedidos;?> productos</span>
              </h3>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-6 col-lg-3 col-lg-pull-3">
      <div class="card">
        <div class="card-body">
          <div class="media">
            <div class="media-middle media-left">
              	<span class="bg-danger circle sq-48">
              		<span class="icon icon-usd"></span>
            	</span>
            </div>
            <div class="media-middle media-body">
              <h6 class="media-heading">Ventas totales</h6>
              <h3 class="media-heading">
                <span class="fw-l">$<?php echo money_format('%.2n', $total);?></span>
              </h3>
            </div>
          </div>
        </div>
      </div>
    </div>
    
</div>

<hr>


<div class="row gutter-xs">

    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
          <h4 class="card-title">Ventas</h4>
        </div>
        <div class="card-body">
          <div class="card-chart"><iframe class="chartjs-hidden-iframe" style="width: 100%; display: block; border: 0px none; height: 0px; margin: 0px; position: absolute; left: 0px; right: 0px; top: 0px; bottom: 0px;"></iframe>
                <canvas id="demo-sales" data-chart="bar" data-animation="false" data-labels='<?php echo $graphic['x'];?>' data-values='[{"label": "Sales", "backgroundColor": "#d9831f", "borderColor": "#d9831f",  "data": <?php echo $graphic['y'];?>}]' data-hide='["legend", "scalesX"]' height="150"></canvas>
          </div>
        </div>
      </div>
    </div>
</div>


<div class="row gutter-xs">
	<div class="col-md-6">
	  <div class="card">
	    <div class="card-header">
	      <div class="card-actions">
	        <button type="button" class="card-action card-toggler" title="Collapse"></button>
	        <button type="button" class="card-action card-reload" title="Reload"></button>
	        <button type="button" class="card-action card-remove" title="Remove"></button>
	      </div>
	      <strong>Sales / Top Brands</strong>
	    </div>
	    <div class="card-body">
	      <div class="row">
	        <div class="col-md-6 m-y">
	          <ul class="list-group list-group-divided">
	            <li class="list-group-item">
	              <div class="media">
	                <div class="media-middle media-body">
	                  <h6 class="media-heading">
	                    <span class="text-muted">Women's Clothing</span>
	                  </h6>
	                  <h4 class="media-heading">28%
	                    <small>$43,498.69</small>
	                  </h4>
	                </div>
	                <div class="media-middle media-right">
	                  <span class="bg-danger circle sq-40">
	                    <span class="icon icon-female"></span>
	                  </span>
	                </div>
	              </div>
	            </li>
	            <li class="list-group-item">
	              <div class="media">
	                <div class="media-middle media-body">
	                  <h6 class="media-heading">
	                    <span class="text-muted">Men's Clothing</span>
	                  </h6>
	                  <h4 class="media-heading">19%
	                    <small>$29,516.97</small>
	                  </h4>
	                </div>
	                <div class="media-middle media-right">
	                  <span class="bg-danger circle sq-40">
	                    <span class="icon icon-male"></span>
	                  </span>
	                </div>
	              </div>
	            </li>
	            <li class="list-group-item">
	              <div class="media">
	                <div class="media-middle media-body">
	                  <h6 class="media-heading">
	                    <span class="text-muted">Computers</span>
	                  </h6>
	                  <h4 class="media-heading">15%
	                    <small>$23,302.87</small>
	                  </h4>
	                </div>
	                <div class="media-middle media-right">
	                  <span class="bg-danger circle sq-40">
	                    <span class="icon icon-laptop"></span>
	                  </span>
	                </div>
	              </div>
	            </li>
	          </ul>
	        </div>
	        <div class="col-md-6 m-y">
	          <table class="table table-borderless table-fixed">
	            <tbody>
	              <tr>
	                <td class="col-xs-1 text-left">1.</td>
	                <td class="col-xs-6 text-left">
	                  <a class="link-muted" href="#">
	                    <span class="truncate">Banana Republic</span>
	                  </a>
	                </td>
	                <td class="col-xs-5 text-right">$7,124.23</td>
	              </tr>
	              <tr>
	                <td class="col-xs-1 text-left">2.</td>
	                <td class="col-xs-6 text-left">
	                  <a class="link-muted" href="#">
	                    <span class="truncate">Calvin Klein</span>
	                  </a>
	                </td>
	                <td class="col-xs-5 text-right">$6,389.26</td>
	              </tr>
	              <tr>
	                <td class="col-xs-1 text-left">3.</td>
	                <td class="col-xs-6 text-left">
	                  <a class="link-muted" href="#">
	                    <span class="truncate">Ralph Lauren</span>
	                  </a>
	                </td>
	                <td class="col-xs-5 text-right">$5,826.64</td>
	              </tr>
	              <tr>
	                <td class="col-xs-1 text-left">4.</td>
	                <td class="col-xs-6 text-left">
	                  <a class="link-muted" href="#">
	                    <span class="truncate">Tommy Hilfiger</span>
	                  </a>
	                </td>
	                <td class="col-xs-5 text-right">$5,064.62</td>
	              </tr>
	              <tr>
	                <td class="col-xs-1 text-left">5.</td>
	                <td class="col-xs-6 text-left">
	                  <a class="link-muted" href="#">
	                    <span class="truncate">Lenovo</span>
	                  </a>
	                </td>
	                <td class="col-xs-5 text-right">$4,536.72</td>
	              </tr>
	            </tbody>
	          </table>
	        </div>
	      </div>
	    </div>
	  </div>
	</div>

</div>



<div class="row gutter-xs">
	<div class="col-md-4 col-md-push-4">
	  <div class="card">
	    <div class="card-header">
	      <div class="card-actions">
	        <button type="button" class="card-action card-toggler" title="Collapse"></button>
	        <button type="button" class="card-action card-reload" title="Reload"></button>
	        <button type="button" class="card-action card-remove" title="Remove"></button>
	      </div>
	      <strong>Most Sold Products</strong>
	      <span aria-hidden="true"> · </span>
	      <a href="#">View full report</a>
	    </div>
	    <div class="card-body">
	      <ul class="media-list">
	        <li class="media">
	          <div class="media-middle media-left">
	            <a href="product.html">
	              <img class="img-circle" width="48" height="48" src="img/5991713086.jpg" alt="Maliha Elephant T-shirt">
	            </a>
	          </div>
	          <div class="media-middle media-body">
	            <h5 class="media-heading">
	              <a class="link-muted" href="product.html">Maliha Elephant T-shirt Women's S-XL #4909</a>
	            </h5>
	            <small>197 Items
	              <span class="rating">
	                <span class="icon icon-star"></span>
	                <span class="icon icon-star"></span>
	                <span class="icon icon-star"></span>
	                <span class="icon icon-star"></span>
	                <span class="icon icon-star"></span>
	              </span>
	            </small>
	          </div>
	        </li>
	        <li class="media">
	          <div class="media-middle media-left">
	            <a href="product.html">
	              <img class="img-circle" width="48" height="48" src="img/5774898501.jpg" alt="Sri Elephant T-shirt">
	            </a>
	          </div>
	          <div class="media-middle media-body">
	            <h5 class="media-heading">
	              <a class="link-muted" href="product.html">Sri Elephant T-shirt Men's S-2XL #4323</a>
	            </h5>
	            <small>165 Items
	              <span class="rating">
	                <span class="icon icon-star"></span>
	                <span class="icon icon-star"></span>
	                <span class="icon icon-star"></span>
	                <span class="icon icon-star"></span>
	                <span class="icon icon-star-half-o"></span>
	              </span>
	            </small>
	          </div>
	        </li>
	        <li class="media">
	          <div class="media-middle media-left">
	            <a href="product.html">
	              <img class="img-circle" width="48" height="48" src="img/6711938749.jpg" alt="Tess Elephant T-shirt">
	            </a>
	          </div>
	          <div class="media-middle media-body">
	            <h5 class="media-heading">
	              <a class="link-muted" href="product.html">Tess Elephant T-shirt Women's S-XL #4972</a>
	            </h5>
	            <small>125 Items
	              <span class="rating">
	                <span class="icon icon-star"></span>
	                <span class="icon icon-star"></span>
	                <span class="icon icon-star"></span>
	                <span class="icon icon-star"></span>
	                <span class="icon icon-star-o"></span>
	              </span>
	            </small>
	          </div>
	        </li>
	      </ul>
	    </div>
	  </div>
	</div>
</div>

<script src="js/vendor.min.js"></script>
<script src="js/elephant.min.js"></script>
